def _ _ main _ _ ( ) : return
from collections import deque
from random import randint
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
# uniform random values in uniform distribution
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
# uniform random values in uniform distribution
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
# uniform random values in uniform distribution
