def gcj2010.r1a ( ) :
    import os
    import sys
    import os
    import os.path
    import time
    import termios
    import time
    import sys
    import termios
    import time
    import time
    import string
    import string
    import string
    import string
    import string
    import time
    import time
    import string
    import string
    import string
    import string
    import string
    import time
    import time
    import time
    import string
    import time
    import time
    import time
    import string
    import os
    import subprocess
    import subprocess
    import subprocess
    import subprocess
    import subprocess
    import subprocess
    import tempfile
    import time
    import time
    import time
    import time
    import time
    import time
    import time
    import time
    import time
    import time
    import time
    import math
    import math
    import time
    import time
    import time
    import time
    import os
    import os
    import sys
    import os
    import time
    import time
    import time
    import math
    import math
    import time
    import time
    import time
    import os
    import subprocess
    import os
    import sys
    import time
    import math
    import math
    import time
    import time
    import time
    import math
    import math
    import time
    import time
    import time
    import os
    import sys
    import time
    import math
    import math
    import time
    import math
    import time
    import os
    import sys
    import time
    import math
    import math
    import time
    import math
    import time
    import math
    import time
    import math
    import time
    import os
    import sys
    import time
    import math
    import math
    import time
    import math
    import time
    import os
    import sys
    import time
    import math
    import time
    import math
    import math
    import time
    import os
    import sys
    import time
    import math
    import math
    import time
    import math
    import os
    import sys
    import time
    import math
    import time
    import math
    import string
    import sys
    import os
    import sys
