def __main ( ) :
    import sys
    from sympy.utilities.iterables import iterables
    from sympy.printing.latex import latex
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import latex
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import latex
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import latex
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import latex
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import latex
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import latex
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import latex
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import pprint_log
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import printinfo
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import printinfo
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import pprint_log
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import printinfo
    from sympy.printing.debughelpers import printinfo
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import pprint_log
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import printinfo
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import pprint_log
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import pprint_log
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import pprint_log
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import pprint_log
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import pprint_log
    from sympy.printing.debughelpers import printinfo
    from sympy.core.printing import pprint_log
    from sympy.printing.debughelpers import pprint_log
    printinfo ( pprint_log )
