def _import ( ) : return _import ( )
from collections import deque
from collections import deque
from collections import defaultdict
from collections import deque
from collections import defaultdict
from collections import deque
from collections import defaultdict
from collections import defaultdict
from collections import deque
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import List
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import List
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
