static final int getDistance ( ) {
  final int xsign = - xsign ;
  final int ysign = - ysign ;
  int [ ] [ ] line ;
  int [ ] [ ] currloc = new int [ 2 ] [ 2 ] ;
  int [ ] [ ] nextloc = new int [ 2 ] [ 2 ] ;
  int i , j ;
  int start ;
  int nextloc = 0 ;
  int [ ] [ ] line = new int [ 2 ] [ 2 ] ;
  int [ ] [ ] line = new int [ 2 ] [ 2 ] ;
  int [ ] [ ] row = new int [ 2 ] [ 2 ] ;
  int [ ] row = new int [ 2 ] [ 2 ] ;
  int [ ] row = new int [ 2 ] [ 2 ] ;
  int [ ] row = new int [ 2 ] [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  int [ ] row = new int [ 2 ] ;
  row [ 0 ] = row [ 0 ] ;
  row [ 1 ] = row [ 1 ] ;
  row [ 0 ] = row [ 1 ] ;
  row [ 1 ] = row [ 2 ] ;
  row [ 2 ] = row [ 3 ] ;
  row [ 3 ] = row [ 4 ] ;
  row [ 4 ] = row [ 5 ] ;
  row [ 5 ] = row [ 6 ] ;
  row [ 6 ] = row [ 7 ] ;
  row [ 7 ] = row [ 8 ] ;
  row [ 8 ] = row [ 9 ] ;
  row [ 9 ] = row [ 10 ] ;
  row [ 10 ] = row [ 11 ] ;
  