def import import _sys , _sys , _readline , _sys , _StopIteration , _StopIteration :
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    from itertools import islice
    