def import import StringIO
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from itertools import islice
from from from from from from from