def _import ( ) : return open ( filename_in , 'rb' )
def _import ( fileobj , fileobj ) : return fileobj
def _has_next_byte ( ) : return True
def buflen ( ) : return 0
try :
    ptr = fileobj.read ( BUFSIZE )
def _readline ( ) : return b''
def _read_char ( ) : return b''
def _read_char ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b''
def _read_long ( ) : return b'