def _ _ main _ _ ( ) : return sys.stdin
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import time
import time
import time
import time
import time
import numpy
import time
import time
import time
import time
import numpy
import numpy
import time
import time
import numpy
import numpy
import numpy
import random
import numpy
import random
import numpy
import numpy
import time
import time
import time
import numpy
import numpy
import numpy
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.random as np
import numpy.random
import numpy.random as np
import numpy.random as np
import numpy.random
import numpy.random as np
import numpy.random as np
import numpy.random as np
from itertools import count
from itertools import count , count , count , count , count , count , count , count
