def _import ( ) : return
from StringIO import StringIO
from random import randint
from time import time
from math import radians
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
