def import import struct
from collections import defaultdict
from collections import defaultdict
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.remove import exists
from os.path import exists
from os.path import exists
from os.remove import exists
