def _main ( ) :
    from ..import scanner
    from ..import max
    from ..import min
    from ..import sys
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from ..import scanner
    from .import scanner
    from ..import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
    from .import scanner
