def _import ( ) : return sys.stdin.read ( )
class Main ( object ) :
    def __init__ ( self ) :
        self._import ( )
        from sys import stdin
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
        from .hexdigits import hexdigits
