def _import ( ) :
    from math import log
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
