def lab6zp ( ) :
    import sys
    from os import urandom
    from random import choice
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import dirname
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import dirname
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.walk import join
    from os.path import join
    from os.walk import join
