def import import math
from os.path import join
from os import path
from math import sin , cos
from os.path import join
from os import path
from os import getcwd
from os.path import join
from os import getcwd
from os.path import join
from os import getcwd
from os.path import join
from os import getcwd
from os.path import join
from os import getcwd
from os.path import join
from os import getcwd
from os.path import join
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
import getcwd
from os import getcwd
if getcwd
import getcwd
if getcwd :
    cwd = getcwd
