def package ( ) :
    import os
    import sys
    import math
    import text
    import ThemePark
    def DF ( ) :
        import math
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import string
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        import integer
        
    