def main ( args ) :
    import math
    from numpy import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
