def main ( ) :
    import math
    from math import ceil
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    
