def _import ( ) :
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import join
    from os import getenv
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    getcwd
    from os import getcwd
    if getcwd ( ) :
        getcwd ( )
    else :
        getcwd ( )
    return getcwd ( )
