def _import ( ) : return _import ( )
import sys
from os import urandom
from random import randint
from time import sleep
from random import uniform
from random import uniform
from random import uniform
from random import choice
from random import choice
from random import choice
from random import uniform
from random import choice
from random import uniform
from random import choice
from random import choice
from random import choice
from random import uniform
from random import choice
from random import choice
from random import uniform
from random import choice
from random import uniform
from random import choice
from random import choice
from random import choice
from random import uniform
from random import choice
from random import uniform
from random import choice
from random import choice
from random import uniform
from random import choice
from random import choice
from random import uniform
from random import choice
from random import uniform
from random import choice
from random import choice
from random import uniform
from random import choice
from random import uniform
from random import choice
from random import uniform
from random import uniform
from random import choice
from random import uniform
from random import uniform
from random import uniform
from random import choice
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
from random import uniform
