def _import ( ) : return sys.stdin
import StringIO
import struct
import struct
import time
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct
from struct import Struct
from struct import Struct
from struct
from struct import Struct
from struct import Struct
from struct
