def import import sys , StringIO , D
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os.path import expanduser
from os.path import join
from os import path as path_expanduser
from os.path import join
from os.path import join
from os import path as path_expanduser
from os.path import join
from os import getcwd
from os import chdir
from os import getcwd
from os.path import join
from os import getcwd
from os.path import join
from os import chdir
from os import getcwd
from os import chdir
from os import getcwd
from os import chdir
from os import getcwd
from os import chdir
from os import getcwd
from os import chdir
from os import getcwd
from os import chdir
from os import getcwd
from os import chdir
from os import getcwd
from os import chdir
from os import getcwd
from os import getcwd
from os import chdir
from os import getcwd
from os.path import join
from os import getcwd
from os import getcwd
from os import getcwd
from os import getcwd
from os.path import join
from os.path import join
from os import getcwd
from os.path import join
from os.path import expanduser
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import dirname
from os.walk import join
from os.path import join
from os.path import join
from os.path import join
from os.walk import join
from os.path import join
from os.path import join
from os.walk import join
from os.path import join
from os.walk import join
from os.path import join
from os.walk import join
from os.path import join
from os.walk import join
from os.path import join
from os.walk import join
if hasattr ( join , '__file__' ) :
    join ( join ( join ( dirname ( abspath ( __file__ ) ) , join ( dirname ( __file__ ) ) , join