def _import ( ) :
    from os import popen , pipes
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
    from .utils import default_stdout
