def _import ( ) :
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    getenv = getenv
    from os import getenv
    getenv = getenv
    from os import getenv
    getenv = getenv
    from os.path import join
    getenv = getenv
    from os.path import join
    getenv = getenv
    print ( getenv )
