def _ _ main _ _ ( ) : return sys.stdout.write
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
import unicode2str
