def _main ( ) :
    import sys
    from numpy.core import zeros , array
    from numpy.core import solve
    from numpy.core import zeros
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import zeros
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    from numpy.core import solve
    solve ( solve ( ) )
