def main ( ) :
    import sys
    solve ( )
    from math import ceil
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
