def _import ( s ) : return s
import defaultdict
import os
import os
import stat
import defaultdict
import operator
import defaultdict
class PowerSwapper ( Scanner ) :
    PROBLEM_NAME = 'power'
    WORK_DIR = r'D:\\'+PROBLEM_NAME+' \ \'
    def __init__ ( self , p , ops ) :
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
        self.p = [ ]
