def _main ( ) :
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
    from collections import defaultdict
