def main ( ) :
    import sys
    from os import path
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import isfile
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import dirname
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import dirname
    from os.path import join
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.isfile import isfile
    from os.path import isfile
    from os.isfile import isfile
    from os.path import isfile
    from os.isfile import isfile
    from os.path import isfile
    from os.isfile import isfile
    from os.path import isfile
    from os.isfile
    from os.path import isfile
