def import _readline
import readline
import sys
from os.path import expanduser
from os.environ import environ
from os.environ import environ
from os.environ import environ
from os.environ import environ
from os.environ import environ
from os.environ import environ
from os.environ import copy
from os.environ import environ
from os.environ import copy
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
from os.environ import pop
pop = pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( 'os.environ' )
pop ( ' os.