def _solve ( ) :
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
