def _ _ main _ _ ( ) : return sys.stdout.write ( int ( next ( ) + next ( ) ) * 2 )
def main ( ) : return sys.stdout.write ( int ( next ( ) ) + next ( ) ) * 2
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write ( "\n" )
def write ( ) : return sys.stdout.write (