static final String print ( int i , String str , int [ ] [ ] e ) {
  int tr , inf , mod ;
  int a , b ;
  int i ;
  int i ;
  int i = i ;
  int j ;
  int i ;
  int inf = 10 ;
  int mod = 10 ;
  i = i ;
  i = i - inf ;
  i = i ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  i = i + inf ;
  