def main ( ) :
    import sys
    from os import getenv
    from os import chdir
    from os import chdir
    from os import environ
    from os import chdir
    from os import chdir
    class Main ( object ) :
        def __init__ ( self ) :
            import sys
            import random
            from random import randint
            from random import randint
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
            from math import log
    