def main ( ) :
    import sys
    from math import sin , cos , cos , log
    from os import urandom
    from os.path import join , exists
    from os.path import getsize
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import isfile
    from os.path import join
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os import sep
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import join
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.isfile import isfile
    from os.path import isfile
    from os.path import isfile
    from os.isfile import isfile
    from os.path import isfile
    from os.isfile import isfile
    from os.path import isfile
    from os.isfile ( join ( join ( isfile , isfile , isfile , isfile , isfile , isfile ) )