def test_expensive_dinner ( ) :
    from sympy.utilities.lambdify import NUMPY_FILES
    from sympy.polys.polyutils import solve
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
    from sympy.polys.polyutils import polyutils
