def _import ( ) :
    from io import BytesIO
    from os import urandom
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
