def scanint ( ) : return int ( scanstring ( ) )
def scanlong ( ) : return scanlong ( )
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def exit ( ) : return 1
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def exit ( ) : return 1
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def exit ( ) : return 1
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return [ ]
def solve ( ) : return solve
