def import import sys
class Main ( object ) :
    def __init__ ( self ) :
        self.all_num = sys.argv [ 1 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 2 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 3 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 4 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 5 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 6 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 7 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 8 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
    def __init__ ( self ) :
        self.all_num = sys.argv [ 9 ]
