def _ _ main _ _ ( ) : return sys.stdin
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import time
import time
import time
import time
import time
import time
import time
import time
import time
import time
import time
import stdin , readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import readline
import readline
import py2exe
import readline
import py2exe
import readline
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import readline
import py2exe
import readline
import py2exe
import py2exe
import py2exe
import readline
import py2exe
import py2exe
import py2exe
import readline
import py2exe
import readline
import py2exe
import readline
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import readline
import py2exe
import readline
import py2exe
import readline
import py2exe
import readline
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
import py2exe
