def _import ( ) :
    import time
    import sys
    import math
    import os
    import os
    import sys
    import time
    import time
    import sys
    import os
    import sys
    import time
    import time
    import sys
    import struct
    import struct
    import time
    import sys
    import struct
    import time
    import sys
    import struct
    import time
    import sys
    import struct
    import struct
    import time
    import time
    import time
    import time
    import sys
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    struct = struct
    import struct
    import struct
    struct = struct
    import struct
    struct = struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from from from struct
    
