def _import ( ) :
    import os
    import os
    import sys
    import os
    import os
    import sys
    import os
    import math
    import os
    import os
    import sys
    import os
    import os
    import sys
    import os
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import os
    import string
    import string
    import math
    import string
    import string
    import string
    import os
    import sys
    import os
    import os
    import sys
    import os
    import os
    import sys
    import os
    import sys
    import os
    import errno
    import math
    import struct
    import time
    import time
    import time
    import time
    import time
    import random
    import math
    import time
    import time
    import time
    import time
    import time
    import math
    import random
    import struct
    from math import sin , cos , sin , cos , sin , cos , sin , cos , sin , cos , sin , cos , sin , cos , sin , cos , sin , cos , sin , cos , sin , cos , sin , cos , sin , cos , sin , sin , cos , sin , cos , sin , sin , cos , sin , cos , sin , sin , sin , cos , sin , sin , sin , cos , sin , sin , cos , sin , sin , sin , cos , sin , sin , sin , sin , cos , sin , sin , cos , sin , sin , sin , sin , cos , sin , sin , sin , cos , sin , sin , sin , sin , cos , sin , sin , sin , sin , cos , sin , sin , cos , sin , sin , sin , cos , sin , sin , cos , sin , sin , cos , sin , sin , sin , cos , sin , sin , cos , sin , sin , sin , cos , sin , sin , sin , cos , sin , sin , cos , sin , sin , sin , cos , sin , sin , cos , sin , sin , sin , sin , cos , sin , sin , sin , sin , sin , sin , sin , sin , sin , cos , sin , sin , sin , sin , sin , sin , sin , sin , sin , sin , sin , sin , sin , sin , sin , sin , cos , ""