def _import ( ) : return _import ( )
import sys
import struct
import sys
import math
import struct
import sys
import sys
import struct
import sys
import sys
import struct
import sys
import struct
import string
import string
import string
import string
import sys
import sys
import struct
import sys
import struct
import struct
import sys
import struct
import struct
import struct
import struct
import struct
import sys
import struct
import struct
import struct
import sys
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
from struct
import struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from from struct
import struct
from struct
import struct
from struct
class None :
    def __init__ ( self , struct ) :
        self.data = None
    def __repr__ ( self ) :
        return ''
    def __init__ ( self ) :
        self.data = None
