def round1c ( ) :
    import io
    import readline
    import readline
    import readline
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    import readline.parse_and_log
    from readline.parse_and_log import parse_and_log
