def _import ( ) :
    from sys import stdin
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import choice
    from random import randint
    from random import randint
    from random import randint
    from random import choice
    from random import randint
    from random import randint
    from random import randint
    from random import choice
    from random import randint
    from random import randint
    from random import choice
    from random import randint
    from random import randint
    from random import choice
    from random import randint
    from random import randint
    from random import choice
    from random import randint
    from random import randint
    from random import randint
    from random import choice
    from random import choice
    from random import randint
    from random import randint
    from random import choice
    from random import randint
    from random import randint
    from random import randint
    from random import choice
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import uniform
    from random import randint
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
