def _ ( ) : return float ( next ( ) )
import sys
from struct import calcsize , unpack
from struct import Struct , calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct
class Struct ( Struct ) :
    def __init__ ( self ) :
        Struct = Struct
