static int n , int d , int k = ( int ) -> {
  int [ ] [ ] lr = new int [ d ] [ k ] ;
  for ( int i = 0 ;
  i < lr . length ;
  i ++ ) lr [ i ] = new int [ n ] [ d ] ;
  for ( int i = 0 ;
  i < lr . length ;
  i ++ ) st [ i ] = new int [ k ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 0 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 1 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 0 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 1 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 0 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 1 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 0 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 1 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 0 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 1 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 0 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] [ 1 ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] = new int [ n ] ;
  for ( int i = 0 ;
  i < st . length ;
  i ++ ) st [ i ] = new int [ n ] ;
  for ( int i