def _import ( ) :
    from os import listdir
    from os import getcwd
    from os import listdir
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import sep
    from os.path import join
    from os import sep
    from os import chdir
    from os import environ
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    cwd = getcwd
    from os import getcwd
    from os import getcwd
    if getcwd ( ) != getcwd ( ) :
        cwd = getcwd ( )
    return getcwd ( )
