def main ( * orange ) :
    import sys
    import os
    import sys
    class A ( object ) :
        def __init__ ( self ) :
            self.name = 'A'
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
            self.nums = [ ]
