def main ( ) :
    import math
    class Main ( object ) :
        @ staticmethod
        def __init__ ( self ) :
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
            from math import sqrt
    