def _import ( ) : return ''
import sys
from io import open
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
