def test_C_as ( ) :
    import locale
    import random
    import locale
    import locale
    import time
    import sys
    import locale
    import locale.getpreferredencoding ( )
    import locale.setlocale
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_MESSAGES
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
    import locale.LC_ALL
