def _import ( ) :
    from sys import stdin as stream
    from io import BytesIO
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct
