def _main ( args ) : return sys.stdin.read ( )
def _INPUT ( ) : return sys.stdin.read ( )
def _solve ( ) :
    n , m = ni ( ) , ni ( )
    map = nm ( n , m )
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
    def _unpack ( ) : return ''
