def _import ( ) : return 33 <= c <= 126
def has_next_byte ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return False
def __next__ ( ) : return False
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return False
def __next__ ( ) : return False
def __next__ ( ) : return False
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return False
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return True
def __next__ ( ) : return __next__
def __next__ ( ) : return True
def __next__ ( ) : return __next__
def __next__ ( ) :
def __next__ ( ) : return True
