def _main ( ) : return
def _dfs1 ( v , p ) : return _dfs1 ( v , p )
def _solve ( ) : return _dfs1 ( v , p )
def _solve ( ) : return _dfs1 ( v , p )
def _solve ( ) : return _dfs1 ( v , p )
def _solve ( ) : return _dfs1 ( v , p )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve ( )
def _solve ( ) : return _solve (