def _main ( ) :
    from time import time
    from os import environ
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
