def _import ( ) : return
from StringIO import StringIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
