def _import ( filter ) : return filter ( lambda ch : ch == ' ' , '\n' , '\r' , '\t' )
from io import StringIO
from io import BytesIO
from io import IOBase
from io import IOBase
from io import IO
from io import IO
from io import IOBase
from io import IO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import IOBase
from io import IO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import IO
from io import StringIO
from io import IO
from io import StringIO
from io import IO
from io import StringIO
from io import IO
from io import IO
from io import IO
from io import StringIO
from io import StringIO
from io import IO
from io import StringIO
from io import IO
from io import StringIO
from io import StringIO
from io import IO
from io import IO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
