def import import sys , string , randrange
from time import sleep
from random import randint
from time import sleep
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue
from queue import Queue

