def _ _ import _ _ ; SPACETOKEN import SPACETOKEN sys SPACETOKEN as SPACETOKEN sys
def _pony ( ) :
    import sys
    import random
    import random
    import pony
    import pony
    import pony.input
    import pony.input
    import pony.output
    import pony.input
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
    import pony.output
