def main ( ) :
    import sys
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
