def _ ( ) : return
import sys
import os
from nlarr import nlarr
from nlarr import nlarr
from nlarr import nlarr
from nlarr import nlarr
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
from nlarr import lcm
