def _import ( ) : return sys.stdin.read ( )
import termios
from time import sleep
from time import sleep
from termios import tcgetattr
from termios import TIOCGWINSZ , termios
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import IOIOIOStream
from io import BytesIO
from io import IOStream
from io import StringIO
from io import StringIO
from io import BytesIO
from io import IOStream
from io import StringIO
from io import StringIO
from io import StringIO
from io import BytesIO
from io import IOStream
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import StringIO
from io import BytesIO
