def exo4 ( ) :
    import os
    import os
    import sys
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
    import chesttypes
