def _ _ main _ _ ( ) : return
class Main ( object ) :
    def __init__ ( self ) :
        self.scn = FastReader ( )
        self.out = ''
        self.INPUT = ''
    def solve ( ) :
        n , mod = self.scn.randint ( ) , self.scn.randint ( )
        self.scn = next ( )
        self.scn.randint ( )
        self.scn = next ( )
        self.scn.randint ( )
        self.scn = next ( )
        self.scn.randint ( )
        self.scn = next ( )
        self.scn.randint ( )
        self.scn = next ( )
        self.scn.randint ( )
        self.scn = next ( )
        self.scn.randint ( )
        self.scn = next ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
        self.scn.randint ( )
    def run ( ) :