def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
def _main ( * o ) : return o
