def _ _ main _ _ ( * args ) : return [ ]
class main ( object ) :
    def __init__ ( self ) :
        sys.stderr.write ( "\n".join ( args ) )
    def __init__ ( self ) :
        self.stream = sys.stdin
        self.stream = sys.stdout
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n" )
        self.stream.write ( "\n"