def main ( args ) :
    import sys
    from os.path import join
    from os import curdir
    import random
    from os.path import join
    from os.path import curdir
    from os.path import join
    from os.path import curdir
    from os.path import curdir
    from os.path import join
    from os.path import curdir
    from os.path import curdir
    from os.path import join
    from os.path import curdir
    from os.path import curdir
    from os.path import join
    from os import curdir
    import random
    from os.path import join
    from os.path import curdir
    from os.path import curdir
    from os.path import join
    from os import curdir
    from os.path import curdir
    from os.path import join
    from os import curdir
    from os.path import join
    from os import curdir
    from os.path import join
    from os import curdir
    from os.path import join
    from os import curdir
    from os.path import join
    from os import getcwd
    from os.path import curdir
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import curdir
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import curdir
    from os.path import join
    from os.path import curdir
    from os.path import join
    from os.path import curdir
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import curdir
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    print ( join ( join ( curdir , join ( curdir , join ( curdir , join ( curdir , join ( curdir , join ( curdir , join ( curdir , join ( curdir , join ( curdir