def _ ( ) : pass
import os
import random
import time
class TaskB ( object ) :
    IFILE = "B-large.in"
    def __init__ ( self ) :
        self.IFILE = "B-large.in"
        self.Scanner = open ( self.IFILE , "r" )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
        self.Scanner.__init__ ( self )
