def _main ( ) :
    from os import getenv
    from os.path import join
    from os import getenv
    from os.path import join
    from os import getenv
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import expanduser
    from os.path import isfile
    from os import sep
    from os.path import join
    from os import sep
    from os.path import join
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os.path import join
    from os.sep import sep
    from os.path import sep
    from os.path import join
    from os.sep import sep
    from os.path import join
    sys.exit ( join ( sys.argv [ 1 : ] ) )
