def _import ( ) :
    import sys
    import getopt
    from os import environ
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
