def _import ( ) : return _import ( '' )
class Main ( object ) :
    def __init__ ( self ) :
        self.n = self.ni
        self.s = self.s + 1
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s )
        self._mergesort_index ( self.ptr , self.s