def main ( ) :
    import sys
    from math import sin , cos , pi
    from os.path import join
    from os import path
    from os.path import join
    from os import path
    from os.path import join
    from os import path
    from os.path import join
    from os import path
    from os.path import join
    from os import path
    from os import path
    from os import getcwd
    from os.path import join
    from os import path
    from os import getcwd
    from os import path
    from os import getcwd
    from os import path
    from os import getcwd
    from os import path
    from os import getcwd
    from os import path
    from os import getcwd
    from os import path
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import path
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.walk import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.walk import dirname
    from os.walk import dirname
    from os.walk import dirname
    from os.path import join
