def main ( ) :
    import sys
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import punctuation
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
