def _import ( ) : return ''
import os
import os
import io
import io
import io
import io
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline.encoding
import readline.readline
import readline.readline
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
import readline.islocal
readline.islocal = True
readline.islocal = False
