def import import sys
class Main ( object ) :
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
    def __init__ ( self ) :
        self.n = sys.argv.index ( 'n' )
