def _main ( args ) :
    from os import stdin
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import random
    from random import randint
    from random import randint
    from random import randint
    from random import random
    from random import randint
    from random import randint
    from random import random
    from random import randint
    from random import random
    from random import randint
    from random import randint
    from random import random
    from random import randint
    from random import randint
    from random import random
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
