def _ _ main _ _ ( ) :
    import io
    import readline
    import readline
    import readline
    import readline
    import readline.math
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    import readline.parse_float
    readline.parse_float.parse_float
