def _import ( ) : return sys.modules [ __name__ ]
import resource
from time import time
MAXN = 500
M = 100003
def __init__ ( self , f , g = None ) :
    self.f = f
    self.g = g
    self.n = MAXN
    self.m = 0
    self.n = MAXN
    self.n = MAXN
    self.m = 0
    self.n = MAXN
    self.n = MAXN
    self.m = 0
    self.n = MAXN
    self.n = MAXN
    self.m = 0
    self.n = MAXN
    self.n = MAXN
    self.m = 0
    self.n = MAXN
    self.n = MAXN
    self.m = m
    self.n = MAXN
    self.n = MAXN
    self.m = n
    self.n = MAXN
    self.n = MAXN
    self.m = m
    self.n = MAXN
    self.n = MAXN
    self.m = n
    self.n = MAXN
    self.n = MAXN
    self.m = m
    self.n = MAXN
    self.s = [ ]
    self.n = 1
    self.m = 0
    self.n = MAXN
    self.m = m
    self.n = MAXN
    self.n = MAXN
