def import import _gcd , _readline
from _readline import readline
from _readline import readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline as _readline
from _readline import _readline
from _readline import _readline
from _readline import _readline
from from _readline import _readline as _readline
from _readline import _readline
