def main ( ) :
    import os
    from sys import stdin
    from os.path import expanduser
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.import exists
