def main ( ) :
    import sys
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
