def main ( ) :
    import time
    import sys
    import os
    import os.path
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import time
    os.environ [ 'PATH_INFO' ] = os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import time
    os.environ [ 'PATH_INFO' ] = os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ]
    import os.environ [ 'PATH_INFO' ] = os.environ [ 'PATH_INFO' ]
    os.environ [ 'PATH_INFO' ] = os.environ [ 'PATH_INFO' ]
    os.environ [ 'PATH_INFO' ]