def main ( ) : pass
import os
import sys
import time
import sys
import os
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import sys
import os
import sys
import subprocess
import subprocess
import subprocess
import subprocess
import sys
import time
import time
import time
import time
import sys
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import os
import sys
import os
import sys
import os
import sys
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import os
import sys
import os
import sys
import time
import time
import time
import time
import time
import time
import time
import time
import time
import time
import time
import time
import sys
import subprocess
import subprocess
import subprocess
import subprocess
import os
import sys
import os
import os
import sys
import os
import time
import time
import time
import time
import time
import time
import time
import subprocess
import subprocess
import os
import sys
import os
import sys
import os
import time
import time
import time
import time
import time
import rtime
from time import time
import time
from time import time
import rtime
from time import time
from time import time
from from SPACETOKEN import SPACETOKEN time
import SPACETOKEN as SPACETOKEN _ _ future _ _ SPACETOKEN import SPACETOKEN _ _ future _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _ SPACETOKEN as SPACETOKEN _ _ future _ _ _
