def _import ( ) :
    from sys import stdin as sys
    from os import urandom
    from os import fdopen
    from os.path import expanduser
    from os.environ import environ
    from os.environ import environ
    from os.fdopen import fdopen
    from os.dup2 import dup2readline
    from os.dup2 import dup2readline
    from os.dup3 import dup2readline
    from os.dup2 import dup2readline
    from os.dup3 import dup2readline
    from os.dup4 import dup2readline
    from os.dup2ascii import ascii as ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
    from os.dup2ascii import dup2ascii
