def import import sys , string , traceback
from os import urandom
from os import urandom
from random import randint
from sys import stdin , stdout
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from random import random
from os import urandom
from os import urandom
from random import randint
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os.path import expanduser
from os.path import join
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os.urandom import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os.path import expanduser
from os.path import expanduser
from os.path import urandom
from os.path import expanduser
from os.path import urandom
from os.path import expanduser
from os.path import urandom
from os.urandom
import random
from os.path import expanduser
from os.path import urandom
from os.path import expanduser
from os.path import urandom
from os.path import expanduser
from os.path import expanduser
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.remove import exists
from os.path import exists
from os.remove import exists
from os.remove import exists
