def _solve_simple ( ex ) :
    from io import BytesIO
    from io import StringIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
