def main ( ) :
    from math import ceil
    from os import urandom
    from os import urandom
    from os import urandom
    from random import randint
    from random import randint
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
