def import import sys , out
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
