def main ( ) :
    def _sc ( ) :
        X = _sc ( )
        Y = _sc ( )
        pprint ( X + Y / 2 )
    def _print ( what ) :
        print ( what )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
        print ( "[" + str ( what ) + "] " + str ( what ) )
    print ( "" )
