def _import ( ) :
    from sys import stdin as stream
    from io import BytesIO
    from io import BytesIO
    from math import pow as f
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
    from io import BytesIO
