def _import ( ) :
    from sys import stdin as readline
    from ..scanner import Scanner
    from ..scanner import Printer
    from ..scanner import Scanner
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from ..scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
    from .scanner import isprintable
