def _import ( ) : return _import ( )
import collections
import Queue
import Queue
import Queue
import Queue
import Queue
import Set
import Map
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Map
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Queue
import Comparator
import Comparator
def main ( ) :
    from sys import sys
    sys.stdout = sys.stderr
    sys.stderr = sys.stdout
    sys.stderr = sys.stderr
    sys.exit ( )
def _same ( x , y ) :
    return root ( x ) == root ( y )
