def _ _ main _ _ ( ) : return sys.stdin
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import rcode
import rcode
import rcode
import rcode
import rcode
import rcode
import rcode
import rcode
import rcode
import rcode
import rcode
import readline
import readline
import rcode
import rcode
import rcode
import rcode
import rcode
import rcode
import rcode
import rcode
import readline
import rcode
import readline
import rcode
import rcode
import rcode
import rcode
import rcode
import readline
import rcode
import rcode
import rcode
import readline
import rcode
import rcode
import rcode
import readline
import rcode
import readline
import rcode
import rcode
import readline
import rcode
import rcode
import rcode
import rcode
import readline
import rcode
import rcode
import readline
import rcode
import rcode
import readline
import rcode
import rcode
import rcode
import readline
import rcode
import rcode
import readline
import rcode
import rcode
import readline
import rcode
import readline
import rcode
import rcode
import readline
import rcode
import rcode
import readline
import rcode
import rcode
import readline
import rcode
import rcode
import readline
from rcode._compat as rcode
import rcode
from rcode._compat as rcode
from rcode._compat import rcode
from rcode._compat import rcode
from rcode._compat import rcode
from rcode._compat import rcode
from rcode._compat import rcode
from rcode._compat import rcode
