def import _sum
import sys
class Main ( object ) :
    def __init__ ( self ) :
        self.s = sys.stdin
        self.n , self.k , self.t = self.s.split ( ' ' )
        self.s.append ( self.n )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.n )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.n )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.n )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
        self.s.append ( self.k )
