def main ( ) :
    import sys
    class Main ( object ) :
        def __init__ ( self ) :
            self.player = [ 'X' , 'O' ]
            self.opponent = [ 'O' , 'X' ]
            self.incomplete = False
            self.board = [ ]
            self.checkrow = True
            self.checkcol = True
            self.checkrow = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
            self.checkcol = True
    return Main
