/*
DESCRIPTION="
*/
public static void main ( String [ ] args ) {
  final PrintStream out ;
  final int T ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  final int N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  N = N ;
  // N = N;
  if ( null == args [ N ] ) {
    out = new PrintStream ( args [ N ] ) ;
  }
  else {
    out = new PrintStream ( args [ N ] ) ;
  }
  out . println ( N ) ;
}
