def howlong ( cakecounts ) :
    import os
    import glob
    import numpy as np
    import numpy as np
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.random as _ni
    import numpy.random as _random
    import numpy.random as _random
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.fft as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.fft as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.random as _fft
    import numpy.fft as _fft
    import numpy.fft as _fft
    import numpy.fft as _fft
    import numpy.fft as _fft
    return _fft
