def _ _ main _ _ ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
def _main ( * args ) : return args
