def main ( ) :
    _sc = raw_input
    S = _sc.next ( )
    pprint ( re.match ( "A[a-z]+C[a-z]+" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
    pprint ( re.match ( "AC" , _sc.next ( ) ) )
