def _iter_minval ( * o ) : return int ( next ( o ) )
class SegmentTreeRMQPos :
    def __init__ ( self , n ) :
        self.N = n
        self.M = self.ni
        self.minpos = self.na
        self.b = self.minpos
        self.x1 = self.opt
        self.y2 = self.o
        self.v = self.o
        self.sum = self.o
        self.o = self.o
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
    def main ( self ) :
        self.n = self.n
        self.m = self.m
        self.n = self.n
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
        self.maxpos = self.maxpos
