def main ( ) :
    import sys
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    print ( zeros ( ) )
