def _import ( ) :
    import os
    import sys
    from os import environ
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
    from os import fdopen
