def _import ( stream ) : return stream.read ( )
def _import ( buf ) : return np.array ( [ random.randint ( 0 , n ) for n in range ( n ) ] )
class Main ( object ) :
    def __init__ ( self ) :
        self.stream = stream
        self.stream = stream
        self.stream.seek ( 0 )
        self.stream.seek ( 0 )
        self.stream.read ( 1 )
        self.stream.seek ( 0 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
