static final String getBinaryText ( double f ) {
  final String ret ;
  ret = String . valueOf ( ( int ) f ) ;
  ret += "." ;
  for ( int n = 0 ;
  n < 6 ;
  n ++ ) {
    f *= 10 ;
    ret += String . valueOf ( ( int ) ( f % 10 ) ) ;
  }
  {
    final double p1_y = trX ;
    final double p2_y = trY ;
    final double trX ;
    final double trY ;
    final double p2_x ;
    final double trX ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trX ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trX ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trX ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY ;
    final double trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY ;
    trY = trY