def _import ( ) :
    import sys
    import struct
    import struct
    import time
    import struct
    import sys
    import struct
    import struct
    import os
    import sys
    import time
    import struct
    import struct
    import struct
    import time
    import sys
    import struct
    import struct
    import struct
    import time
    import sys
    import struct
    import struct
    import struct
    import struct
    import struct
    import time
    import time
    import sys
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    struct
    import struct
    import struct
    import struct
    import struct
    struct
    import struct
    import struct
    import struct
    import struct
    
    struct = struct
