def main ( args ) :
    from os import read
    from os import isatty
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
    getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( ) ) ) ) ) ) )