def test_light_scanner ( ) :
    from lasagne.utils import light_scanner
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
    from lasagne.errors import StringWarning
