def _import ( ) : return sys.stdin
import StringIO
import time
import sys
import struct
import struct
import struct
import struct
import sys
import struct
import struct
import struct
import sys
import struct
import struct
import struct
import struct
import sys
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
from time
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
from struct import Struct
from struct
import struct
from struct
from struct
import struct
from struct
from struct SPACETOKEN import SPACETOKEN struct ; SPACETOKEN struct
