def _import ( ) : return _import ( )
def _import ( ) : return _import ( )
def debug ( * args ) : return _import ( )
def _debug ( * args ) : return _import ( )
def _import ( ) :
def _import ( ) :
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
    global _IO
