def _import ( ) : return _import ( )
class Main ( ) :
    def __init__ ( self ) :
        self.N = 0
        self.P = 0
        self.fact = [ ]
        self.inv = [ ]
    def submit ( self ) :
        self.out.write ( fast ( randint ( 1 , P ) ) )
    def test ( self ) :
        self.N = self.N
        self.P = self.P
        self.fact = [ ]
        self.cnt = 1
        self.cnt = self.cnt
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
        self.cnt += 1
