def _import ( ) :
    import os
    import sys
    import os
    import os
    import os
    import sys
    import os
    import time
    import locale
    import tokenize
    import os.environ
    import os
    import sys
    import os
    import time
    import locale
    import tokenize
    import time
    import time
    import sys
    start_time = time.time
    locale.setlocale ( 'en_US' , '' )
    def main ( ) :
        global TASKNAME
        global ID
        global ID
        global HEIGHT
        global CURRENT
        global MOVES
        [ 0 , - 1 ] = ( 'a' + str ( len ( ID ) ) )
        global ID
        global CURRENT
        global ID
        global CURRENT
        global ID
        global CURRENT
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global ID
        global CURRENT
        global ID
        global ID
        global ID
        global ID
        global ID
        global ID
    