def main ( ) :
    import sys
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
    from binascii import b2s
