def _import ( ) : return sys.stdin
import io
import StringIO
import io
import set
import io
import io
import StringIO
import io
import StringIO
import io
import sys
import warnings
import warnings
import os
import sys
import os
import sys
import os
import string
import string
import string
import StringIO
import io
import codecs
import warnings
import warnings
import warnings
import warnings
import inspect
import inspect
import inspect
import inspect
import warnings
import warnings
import warnings
import warnings
import inspect
import warnings
import inspect
import warnings
import inspect
import warnings
import inspect
import warnings
import inspect
import warnings
import inspect
import warnings
import inspect
import warnings
import inspect
import warnings
import inspect
import inspect
import warnings
import inspect
import inspect
import warnings
from inspect
import inspect
import inspect
from inspect
import inspect
from inspect
import inspect
import warnings
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from functools
import inspect
from inspect import getLevelName
from inspect
import inspect
from inspect import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from functools
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
import inspect
from inspect
class Dummy :
    if '__main__' in inspect.getmembers ( ) [ 0 ] :
        from inspect import inspect
        return
    class Dummy :
        pass
    class Dummy :
        pass
    return Dummy ( 'Dummy Dummy Class' )
