def import _raw_input
import sys
import os
import sys
import subprocess
import subprocess
import subprocess
import time
import random
import shlex
import random
import random
import random
import string
import random
import random
import random
import string
import sys
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import time
import time
import random
import random
import string
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import sys
import time
import time
import time
import random
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import sys
import time
import time
import time
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import sys
import subprocess
import time
import time
import time
import random
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import sys
import time
import string
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import sys
import time
import time
import random
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import sys
import time
import time
import random
import sys
import string
import sys
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import time
import sys
import subprocess
import subprocess
from time import time
# read from sys
