def _main ( ) :
    from time import time
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import fdopen
    from os.path import expanduser
    from os.path import join
    from os import urandom
    from os.path import expanduser
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import expanduser
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.urandom
    import urandom
    from os.urandom
    from os.urandom import getuid
    from os.urandom import getuid
    from os.urandom
