public static final double [ ] [ ] getStdoutLines ( ) {
  final ParameterParser ap = new ParameterParser ( ) ;
  final List < String > toks = ap . parse ( ) ;
  toks . clear ( ) ;
  toks . add ( "input" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  toks . add ( "line" ) ;
  Arrays . sort ( toks )