def main ( ) :
    import sys
    from string import string
    from string import ascii_lowercase
    from string import digits
    from string import reverse
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii
    from string import ascii
