def _import ( ) : return _readline
from io import StringIO
from io import BytesIO
from time import sleep
from time import sleep
from random import choice
from random import choice
from random import choice
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
from io import StringIO
