def _import ( ) : return
from itertools import repeat
from itertools import chain
from itertools import chain
from itertools import repeat
from itertools import chain
from itertools import chain
from itertools import repeat
from itertools import chain
from itertools import chain
from itertools import chain
from itertools import repeat
from itertools import chain
from itertools import chain
from itertools import chain
from itertools import chain
from itertools import reduce
from itertools import chain
from itertools import chain
from itertools import chain
from itertools import itertools
from itertools import chain
from itertools import chain
from itertools import itertools
from itertools import next
from itertools import chain
from itertools import chain
from itertools import chain
from itertools import itertools
from itertools import chain
from itertools import itertools
from itertools import next
from itertools import chain
from itertools import itertools
from itertools import next
from itertools import chain
from itertools import itertools
from itertools import chain
from itertools import itertools
from itertools import next
from itertools import chain
from itertools import itertools
from itertools import next
from itertools import itertools
from itertools import chain
from itertools import itertools
from itertools import next
from itertools import itertools
from itertools import next
from itertools import itertools
from itertools import chain
from itertools import itertools
from itertools import next
from itertools import itertools
from itertools import itertools
from itertools import next
from itertools import itertools
from itertools import itertools
from itertools import next
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from itertools import itertools
from from itertools import itertools
from itertools import import itertools
from itertools import itertools
from from itertools import itertools
from from itertools import itertools
from from itertools import import itertools
from from from itertools import itertools
