static final String getOneLine ( String attr , double weight ) throws IOException {
  class Node {
    private final String animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String [ ] animal ;
    private final String animal ;
    private final String [ ] animal ;
    private final String animal ;
    private final String animal ;
    private final String animal ;
    private final String animal ;
    private final String animal ;
    private final String animal ;
    private final String animal ;
    private final String animal ;
    private final String animal ;
    private final String animal ;
    private final String