def main ( ) :
    import random
    import sys
    from os import urandom
    from random import randint
    from random import choice
    from os import urandom
    from os import urandom
    from random import random
    from os import urandom
    from random import random
    from os import urandom
    from random import choice
    from os import urandom
    from random import random
    from os import urandom
    from random import random
    from os import urandom
    from random import random
    from os import urandom
    from random import random
    from os import urandom
    from random import random
    from os import urandom
    from os import urandom
    from random import random
    from os import urandom
    from os import urandom
    from random import random
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.urandom import randint
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.urandom
    import urandom
    from os.urandom import random
    from os.urandom
    from os.urandom import randint
    from os.urandom import urandom
    from os import urandom
