def import _DScoreAttack
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os.path import join
from os import fdopen
from os.path import join
from os import fdopen
from os.path import join
from os import fdopen
from os.path import join
from os import fdopen
from os.path import join
from os import fdopen
from os.path import join
from os import fdopen
from os.path import join
from os import fdopen
from os.path import join
from os import fdopen
from os.path import join
from os import chdir
from os import chdir
from os import getcwd
from os import chdir
from os.path import join
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os import chdir
from os.path import join
from os.path import join
from os.path import expanduser
from os.path import join
from os.path import join
from os.chdir ( chdir )
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.chdir import join
print ( join ( join ( abspath ( join ( sys.argv [ 0 ] ) ) , '..'