def _import ( ) :
    from sys import stdin
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import compat
    from .py3compat import PY3
    from .py3compat import compat
    from .py3compat import PY3
    from .py3compat import compat
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import compat
    from .py3compat import PY3
    from .py3compat import compat
    from .py3compat import PY3
    from .py3compat import compat
    from .py3compat import PY3
    from .py3compat import compat
    from .py3compat import PY3
    from .py3compat import PY3
    from .py3compat import compat
    from .py3compat import PY3
    from .compat import compat
    from .py3compat import PY3
    from .compat import compat
    from .compat import compat
    from .py3compat import PY3
    from .compat import compat
    from .py3compat import PY3
    from .compat import compat
    from .compat import PY2
    from .compat import compat
    from .compat import compat
    from .compat import PY3
    from .compat import compat
    from .compat import PY3
    from .compat import PY3
    from .compat import compat
    from .compat import PY2
    from .compat import compat
    from .compat import PY2
    from .compat import PY3
    from .compat import PY3
    from .compat import PY2
    from .compat import PY3
    from .compat import PY3
    from .compat import PY2
    if PY2 :
        from ._import PY2
    if PY2 :
        from ._import PY2
    return bytes
