def import import sys
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
from telkey import Telkey
