def import import StringIO
import math
import os
import time
import sys
class Main ( object ) :
    def __init__ ( self ) :
        self.stream = sys.stdout
        self.stream = sys.stdin
        self.stream.seek ( 0 )
        self.stream.seek ( 0 )
        self.stream.read ( )
        self.stream.seek ( 0 )
        self.stream.read ( )
        self.stream.seek ( 0 )
        self.stream.read ( )
        self.stream.seek ( 0 )
        self.stream.read ( )
        self.stream.seek ( 0 )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.seek ( 0 )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.seek ( 0 )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
        self.stream.read ( )
