def _main ( * args ) : return _main ( * args )
def _main ( * args ) : return _main ( * args )
def _main ( * args ) : return _main ( * args )
def _main ( * args ) : return _main ( * args )
def _main ( * args ) : return _main ( * args )
def _gen_longs ( n ) : return _main ( * args )
def _gen_longs ( n ) : return _main ( * args )
def _gen_longs ( n ) : return _main ( * args )
def _gen_longs ( n ) : return _main ( * args )
def _gen_longs ( n ) : return _main ( * args )
def _gen_longs ( n ) : return _main ( * args )
def _gen_longs ( n ) : return _main ( * args )
def _gen_longs ( n ) : return _main ( * args )
def _gen_longs ( n ) : return _main ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_longs ( n ) : return _gen_longs ( * args )
def _gen_floats ( n ) : return _gen_longs ( * args )
def _gen_floats ( n ) : return _gen_floats ( * args )
def _gen_floats ( n ) : return _gen_floats ( * args )
def _gen_floats ( n ) : return _gen_floats ( * args )
def _gen_floats ( n ) : return _gen_floats ( * args )
def _gen_floats ( n ) : return _gen_floats ( * args )
def _gen_floats ( n ) : return _gen_floats ( *