def _import ( ) :
    from numpy import zeros , dtype
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
    from numpy.core import fmatrix
