def _import ( ) :
    from StringIO import StringIO
    from random import randint
    from sys import maxsize
    from sys import stdin
    from sys import stderr
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os.environ import environ
    from os.environ import environ
    from os.fdopen import fdopen
    from os.dup2 import dup2read
    from os.dup2bytes import fdopen
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
    from os.dup2bytes import dup2bytes
