def _import ( ) :
    from io import BytesIO
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
