def test_task_a ( ) :
    import sys
    from os import urandom
    from os import fdopen
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.exists import exists
    from os.path import exists
    from os.path import exists
    from os.exists import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.walk import absolute
    absolute = exists ( absolute )
    absolute.remove ( absolute )
