def contest ( ) :
    import os
    import re
    import math
    import os
    import os
    import os
    import re
    import os
    import os
    import os
    import re
    import os
    import os
    import sys
    import os
    import subprocess
    import subprocess
    import subprocess
    import subprocess
    import tempfile
    import os
    import stat
    import time
    import time
    import random
    import string
    import string
    import time
    import time
    import time
    import time
    import time
    import subprocess
    import subprocess
    import subprocess
    import subprocess
    import os
    import sys
    import os
    import subprocess
    import tempfile
    import os
    import tempfile
    import os
    import tempfile
    import tempfile
    import time
    import time
    import time
    import time
    import time
    import time
    import math
    import random
    import time
    import time
    import time
    import time
    import os
    import sys
    import os
    import string
    import string
    import os
    import sys
    import os
    import string
    import os
    import sys
    import os
    import string
    import os
    import sys
    import os
    import errno
    import errno
    import os
    import errno
    import errno
    import os
    import errno
    import os
    import errno
    import os
    import sys
    import errno
    import os
    import errno
    import os
    import errno
    import os
    import errno
    import errno
    import os
    import errno
    import os
    import errno
    import errno
    import errno
    import os
    import sys
    import os
    import errno
    import errno
    import os
    import errno
    import errno
    # from os
    import os
    import errno
    import os
    import errno
    # from os
    import os
    import errno
    import errno
    # from os
    try :
        os.chdir ( os.path.join ( WORK_DIR , "input.txt" ) )
        os.chdir ( os.path.join ( WORK_DIR , "output.txt" ) )
    except :
        os.chdir ( os.path.join ( WORK_DIR , "input.txt" ) )
    try :
        os.chdir ( os.path.join ( WORK_DIR , "output.txt" ) )
    except :
        os.chdir ( os.path.join ( WORK_DIR , "output.txt" ) )
