def import import os
from cStringIO import StringIO
from os import open
from os import devnull
from os import open
from os import devnull
from os import devnull
from os import devnull
from os import open
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
from os import devnull
