def __main ( ) :
    from math import log
    from random import randint
    from time import sleep
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
