def import import sys
class Main ( object ) :
    def __init__ ( self ) :
        self.INF = 1000000000000000000L
    def __call__ ( self , * args ) :
        import sys
        from random import randint
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
        from math import log
    