def _main ( ) :
    import sys
    import os
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import digits
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii
    from string import ascii
    from string import ascii
