def import sys
from os.path import join
from os import urandom
from os.path import join
from os.path import expanduser
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os import getcwd
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
print ( join ( join ( join ( join ( join ( join ( join ( join ( join ( join ( join ( join ( join ( join ( join ( join (