def main ( ) :
    import random
    from numpy.core import get_closest_index
    from numpy.random import randint
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
    from numpy.core import get_closest_index
