def codejam2c ( ) :
    import os
    import sys
    from codecs import open
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    from codecs import BOM_UTF8
    
