def test_baia ( ) :
    import numpy as np
    import scipy.optimize
    import scipy.optimize
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
    import scipy.optimize.baia as baia
