def _import ( ) :
    from time import time
    from os import environ
    from os import getfile
    from os import getuid
    from os import environ
    from os import getuid
    from os import getuid
    from os import getgid
    from os import getgid
    from os import getuid
    from os import getgid
    from os import getgid
    from os import getuid
    from os import getgid
    from os import getgid
    from os import getuid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getuid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
    from os import getgid
