def import _readline
from sys import stdin , stdout
from sys import stderr
from os import urandom
from os import urandom
from random import randint
from os import urandom
from os import urandom
from os import urandom
from random import random
from os import urandom
from random import randint
from os import urandom
from os import urandom
from random import random
from os import urandom
from os import urandom
from random import random
from os import urandom
from os import urandom
from random import random
from os import urandom
from os import urandom
from random import random
from os import urandom
from os import urandom
from random import random
from os import urandom
from os import urandom
from random import randint
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from random import random
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
if urandom is None :
    urandom = urandom ( )
