def _import ( ) : return _import ( )
import sys
import io
import text
import collections
import collections
import random
import string
import random
import random
import string
import random
import math
import random
import random
import string
import math
import random
import random
import string
import random
import string
import random
import string
import random
import random
import string
import math
import random
import random
import sys
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import time
import time
import time
import time
import time
import time
import time
import time
import random
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import subprocess
import os
import sys
import struct
import struct
import struct
import struct
import time
import time
import time
import time
import time
import time
import time
import subprocess
import subprocess
import subprocess
import subprocess
import os
import sys
import subprocess
import subprocess
import time
import time
import time
import time
import time
import math
import random
import StringIO
import struct
import struct
import struct
import struct
import struct
import struct
import string
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import time
import time
import math
import time
import time
import math
import string
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import string
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
from struct
import struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from from SPACETOKEN import SPACETOKEN struct

