def main ( ) :
    import sys
    from random import randint
    from time import sleep
    from math import log
    from math import pi
    from math import log
    from math import log
    from math import pi
    from math import log
    from math import pi
    from math import log
    from math import pi
    from math import log
    from math import pi
    from math import log
    from math import pi
    from math import log
    from math import log
    from math import pi
    from math import log
    from math import log
    from math import pi
    from math import log
    from math import log
    from math import pi
    from math import log
    from math import log
    from math import log
    from math import log
    from math import pi
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
    from math import log
