def _import ( ) : return _import ( )
from sys import stdin
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct
class Struct :
    def __init__ ( self ) :
        super ( Struct , self )
