def _import ( ) :
    from sys import stdin as PIPE
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    # read from the WSGI environment
    environ = environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    # read from the WSGI server
    environ = environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    # read from the WSGI handler
    environ = environ
    from os.environ = environ
    from os._import _import run_simple
