def _import ( ) : return _import ( )
class Main ( object ) :
    def __init__ ( self ) :
        self.n = os.getpid ( )
        self._pack ( self.ptr )
        self.time = self._pack ( )
    def __next_int__ ( self ) :
        self.n = self._randint ( )
        self._randint ( )
        self._randint ( )
        self._randint ( )
        self._randint ( )
        self._randint ( )
        self._randint ( )
        self._flush ( )
        self._readline ( )
        self._readline ( )
        self._readline ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
        self._empty ( )
    def __next_int__ ( self ) :
        self._empty ( )
        self._empty ( )
        self._empty ( )
    def __next_int__ ( self ) :