def _ _ main _ _ ( ) : return True
class Main ( object ) :
    def __init__ ( self ) :
        self.__debug = False
        self.file_name = 'input.txt'
        self.__fast = True
        self.MOD = int ( 1e9 ) + 7
        INF = sys.maxsize / 2
        def solve ( ) :
            self.__fast = False
            self.__fast = True
            self.__fast = False
            self.__fast = False
            self.__fast = True
            self.__fast = False
            self.__fast = True
            self.__fast = False
            self.__fast = True
            self.__fast = True
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = True
            self.__fast = True
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
            self.__fast = False
    def read ( ) :
        self.__fast = True
        self.__fast = True
