def main ( ) :
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
