def _ import _ , out = sys.stdout ) :
    import string
    import sys
    import os
    import sys
    import string
    import sys
    import os
    import sys
    import string
    import string
    import sys
    import struct
    import string
    import struct
    import string
    import struct
    import string
    import struct
    import string
    import struct
    import struct
    import string
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    from struct
    import struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from from struct
    import struct
    from struct
    from struct
    import struct
    from struct
    from struct
    import struct
    from from struct
    
