def main ( ) :
    import math
    import numpy
    from numpy.linalg import norm
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
    from numpy.random import uniform
