def _import ( ) :
    from random import randint
    from math import log
    from os import urandom
    from random import randint
    from random import randint
    from random import choice
    from random import choice
    from random import random
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import random
    from random import choice
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import random
    # we don't know here
