def _import ( ) :
    import random
    import random
    import random
    import random
    import random
    import random
    import random.randint
    import random.randint
    import locale
    class A :
        global THREADS
        global NAME
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        global stdout
        stdout = stdout
    