def import import sys , string , traceback
class Main ( object ) :
    def __init__ ( self ) :
        self.sys = sys.stdin
        self.sys.stdin = sys.stdout
        self.sys.stdin.isatty ( )
        self.sys.stdin = sys.stdin
        self.sys.stdin.isatty ( )
        self.sys.stdin = sys.stdin
        self.sys.stdin.isatty ( )
        self.sys.stdin = sys.stdin
        self.sys.stdin.isatty ( )
        self.sys.stdin = sys.stdin
        self.sys.stdin.isatty ( )
        self.sys.stdin = sys.stdin
        self.sys.stdin.isatty ( )
        self.sys.stdin = sys.stdin
        self.sys.stdin.isatty ( )
        self.sys.stdin = sys.stdin
        self.sys.stdin.isatty ( )
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdout = sys.stdout
        self.sys.stderr = sys.stderr
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdin = sys.stdin
        self.sys.stdout = sys.stdout
        self.sys = self
