def main ( ) :
    import os
    import sys
    import struct
    import struct
    import struct
    import struct
    import os
    import sys
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import sys
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    
    import struct
    import struct
    import struct
    
    import struct
    import struct
    
    import struct
    
