def main ( ) :
    import sys
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 4 )
    from time import sleep
    sleep ( 3 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 4 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    sleep ( 5 )
    sleep ( 5 )
    from time import sleep
    sleep ( 5 )
    sleep ( 5 )
    sleep ( 5 )
    sleep ( 5 )
    sleep ( 5 )
