def main ( ) : return d [ board ]
import sys
import random
import string
import sys
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import csv
import sys
import time
def main ( ) :
    global calc
    global d
    import csv
    import sys
    import csv
    import csv
    import sys
    import struct
    import struct
    import string
    import struct
    import struct
    import time
    import time
    import time
    import time
    import time
    import time
    import string
    import struct
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import time
    import time
    import time
    import time
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import sys
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import time
    import time
    import time
    import csv
    import csv
    import csv
    import csv
    import csv
    import sys
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import sys
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import sys
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import sys
    import csv
    import csv
    import csv
    import csv
    import sys
    import csv
    import csv
    import csv
    import csv
    import csv
    import sys
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import sys
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
    import csv
