def _solve ( ) :
    import sys
    import os
    import os
    import sys
    import os.path
    import sys
    import time
    import queue
    import time
    import time
    import random
    import time
    import time
    import random
    import time
    import random
    import time
    import queue
    import time
    import time
    import random
    import sys
    import time
    import random
    import time
    import random
    import time
    import random
    import sys
    import sys
    import time
    import time
    import random
    import time
    import time
    import random
    import time
    import time
    import random
    import time
    import time
    import random
    import sys
    import sys
    import os
    import sys
    import time
    import time
    import time
    import random
    import time
    import random
    import time
    import time
    import random
    import sys
    import sys
    import sys
    import time
    import time
    import random
    import time
    import time
    import random
    import sys
    import sys
    import time
    import time
    import random
    import time
    import sys
    import sys
    import sys
    import time
    import random
    import time
    import time
    import random
    import sys
    import sys
    import time
    import time
    import random
    import sys
    import sys
    import time
    import random
    import sys
    import sys
    import time
    import random
    import time
    import sys
    import sys
    import sys
    import time
    import random
    import time
    import sys
    import sys
    import time
    import random
    import sys
    import sys
    import sys
    import time
    import random
    import time
    import sys
    import sys
    import sys
    import time
    import random
    import time
    import sys
    import sys
    import time
    import random
    import sys
    import sys
    import sys
    import time
    import random
    import time
    import random
    import sys
    import sys
    import sys
    import os
    import sys
    import time
    import random
    import time
    import random
    import sys
    import sys
    import time
    import random
    import sys
    import sys
    from time import random
    import time
    from time import random
    from time import random
    from time import time
    from time import random
    from sys import maxint
    from time import time
    from from time import sleep
    from time import sleep
    if sys.version >= '1.3.1' :
        sys.exit ( 0 )
    return
