def package ( gcj2012 ) :
    import os , sys
    import time , datetime , time , datetime , datetime , time , real
    from os.path import join
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.sep import sep
    from os.path import join
    from os.sep import sep
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import sep
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import sep
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import join
    from os.path import join
    from os.sep import sep
    from os.path import join
    from os.sep import join
    from os.path import join
    print ( join ( join ( sys.argv ) )