def _import ( ) :
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import chdir
    from os import chdir
    from os import chdir
    from os import getcwd
    from os.path import expanduser
    from os import chdir
    from os import getcwd
    from os.path import expanduser
    from os import getcwd
    from os import chdir
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import expanduser
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import expanduser
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.walk import getcwd
    from os.path import join
    from os.path import dirname
    from os.walk import getcwd
    from os.path import join
    from os.path import join
