def main ( ) :
    import sys
    import os
    import sys
    from math import sin , cos
    from math import cos , sin
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.walk import join
    from os.path import join
    from os.walk import join
