def _import ( ) : return int ( next ( ) )
def _import ( ) : return float ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _eval ( ) : return float ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return float ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return float ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return int ( next ( ) )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) : return eval ( )
def _eval ( ) :
    return eval ( )
