def _import ( ) : return open ( '/dev/null' , 'r' )
def read ( ) : return open ( '/dev/null' , 'r' ).read ( )
def main ( ) :
    fh = sys.stdin
    fh = sys.stdout
    fh = MyInput ( fh )
    fh = open ( fh , 'w' )
    fh.write ( fh )
    fh.seek ( 0 )
    fh.read ( 1 )
    fh.seek ( 0 )
    fh.read ( 1 )
    fh.write ( '-' )
    fh.read ( 1 )
    fh.seek ( 0 )
    fh.read ( 1 )
    fh.write ( '-' )
    fh.read ( 1 )
    fh.write ( '-' )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.write ( '-' )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.write ( '-' )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.write ( '-' )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
    fh.read ( 1 )
