def _ _ main _ _ ( ) : return sys.stdin
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import time
import time
import time
import time
import time
import time
import time
import maxsize
import numpy
import numpy
import numpy
import numpy
import numpy
import numpy
import time
import time
import time
import numpy
import numpy
import numpy
import numpy
import numpy.random
import numpy.random
import numpy.random
import numpy.random
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import readline
import readline
import readline
import readline
import readline
import numpy.testing
import readline
import readline
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import readline
import readline
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import readline
import readline
import readline
import readline
import numpy.testing
import readline
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing
import numpy.testing as numpy
import numpy.testing
import numpy.testing as numpy
import numpy.testing as numpy
import numpy.testing
import numpy.testing as numpy
import numpy.testing as numpy
import numpy.testing as numpy
from numpy.testing._compat import import _DummyWrapper
from numpy.testing import import numpy
