def import import StringIO
from numpy.core import basic
from numpy.core import log
from numpy.core import zeros
from numpy.core import cast
from numpy.core import log
from numpy.core import log
from numpy.core import cast
from numpy.core import log
from numpy.core import log
from numpy.core import cast
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import log
from numpy.core import import log
from numpy.core import log
