def _import ( ) :
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
