def main ( ) :
    import sys
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import string
    import sys
    import string
    import string
    import string
    import string
    import string
    import sys
    import string
    import string
    import string
    import string
    import sys
    import string
    import string
    import string
    import sys
    import string
    import string
    import string
    import sys
    import string
    import string
    import string
    import sys
    import string
    import string
    import sys
    import string
    import string
    import string
    import sys
    import string
    import string
    import sys
    import string
    import string
    import sys
    import string
    import string
    import sys
    import string
    import string
    import sys
    # main()
