def _ _ main _ _ ( ) : return _main ( )
def __init__ ( self , a , b ) : return _main ( )
def __init__ ( self , a , b ) : return _main ( )
def __init__ ( self , a , b ) : return _main ( )
def __init__ ( self , a , b ) : return _main ( )
def __init__ ( self , b , c ) : return _main ( )
def __init__ ( self , a , b ) : return _main ( )
def __init__ ( self , b , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , a , b ) : return _main ( )
def __init__ ( self , c , b ) : return _main ( )
def __init__ ( self , c , c ) : return _main ( )
def __init__ ( self , c , a , b ) : return _main ( )
def __init__ ( self , c , c ) : return