def _import ( ) :
    from os import system , read
    from os.path import join
    from os import sep
    from os import sep
    from os import chdir
    from os import environ
    from os import chdir
    from os import environ
    from os import chdir
    from os import environ
    from os import chdir
    from os import environ
    from os import chdir
    from os import environ
    from os import chdir
    from os import environ
    from os import chdir
    from os import chdir
    from os import environ
    from os import chdir
    from os import chdir
    from os import environ
    from os import chdir
    from os import chdir
    from os import environ
    from os import chdir
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os.path import expanduser
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import join
    from os.path import expanduser
    from os.walk import walk
    from os.path import normpath
    from os.path import join
    from os.path import dirname
    from os.walk import walk
    from os.path import normpath
    from os.path import join
    from os.path import dirname
    from os.walk import normpath
    from os.path import join
    from os.walk import normpath
    from os.path import dirname
    from os.walk import normpath
    from os.path import join
    from os.path import dirname
    from os.walk import normpath
