def main ( ) :
    import sys
    from math import fabs
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from math import pi
    from