def _ _ main _ _ ( ) : return
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
from sympy.polys.distributedmodules import sdm_nf_main
