def import import os , sys , glob , time , count , r
from random import randint
from math import log10
from math import radians
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import sin
from math import log
from math import log
from math import log
from math import log
from math import log
from math import log
from math import sin
from math import log
from math import log
from math import log
from math import log
from math import sin
from math import log
from math import log
from math import sin
import string
from math import string

