def _import ( ) :
    from itertools import repeat
    from itertools import chain
    from os import urandom
    from ctypes import c_int
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes.Struct import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes import Struct
    from ctypes.Struct import Struct
    from ctypes import Struct
    from ctypes.Struct import Struct
    from ctypes import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
    from ctypes.Struct import Struct
