def main ( args ) :
    import sys
    from sympy.utilities.randtest import get_randtest
    from sympy.core.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
    from sympy.sets import Set
