def _ _ main _ _ ( ) :
    import os
    from string import ascii_lowercase , digits
    from string import digits
    from string import ascii_lowercase , digits
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import punctuation
    from string import digits
    from string import punctuation
    from string import digits
    from string import punctuation
    from string import digits
    from string import punctuation
    from string import digits
    from string import punctuation
    from string import digits
    from string import punctuation
    from string import digits
    from string import punctuation
    from string import digits
    from string import digits
    from string import digits
    from string import punctuation
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import punctuation
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import digits
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
    from string import ascii
