def _import ( * os ) : print ( deeprepr ( os ) )
def _import ( * args ) :
    INF = 1001001001
    def solve ( ) :
        N = sc.randint ( 1 , N )
        p = [ [ ] for i in range ( N ) ]
        for x in sc.randint ( 1 , N ) :
            p.append ( [ min ( x , y ) , max ( x , y ) ] )
    class MyScanner ( Scanner ) :
        stream = open ( "/dev/null" , "r" )
        stream.close ( )
        stream = open ( "/dev/null" , "w" )
        stream.close ( )
        stream = open ( "/dev/null" , "r" )
        stream.close ( )
        stream = open ( "/dev/null" , "w" )
        stream.close ( )
        stream = open ( "/dev/null" , "w" )
        stream.close ( )
        stream.close ( )
        stream = open ( "/dev/null" , "w" )
        stream.close ( )
        stream.close ( )
        stream = open ( "/dev/null" , "r" )
        stream.close ( )
        stream.close ( )
        stream = open ( "/dev/null" , "w" )
        stream.close ( )
        stream.close ( )
        stream = open ( "/dev/null" , "w" )
        stream.close ( )
        stream.close ( )
        stream = open ( "/dev/null" , "w" )
        stream.close ( )
        stream.close ( )
        stream.close ( )
        stream = open ( "/dev/null" , "r" )
        stream.close ( )
        stream.close ( )
        stream = open ( "/dev/null" , "w" )
        stream.close ( )
        stream.close ( )
        stream.close ( )
        stream.close ( )
        stream = open ( "/dev/null" , "r" )
        stream.close ( )
        stream.close ( )
        stream.close ( )
        stream.close ( )
    return _import ( s , t )
