def _import ( ) :
    from sys import stdin , stdout
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from time import random
    from time import time
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os import environ
    from os.environ import environ
    from os import environ
    from os.environ import environ
    environ = environ
    from os.environ import environ
    environ = environ
