def _import ( ) : return int ( next ( ) )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return next ( )
def _readline ( ) : return _readline
def _readline ( ) : return _readline
def _readline ( ) : return _readline
def _readline ( ) : return _readline
def _readline ( ) : return _readline
def _readline ( ) : return _readline
def _readline ( ) :
