def main ( ) :
    import math
    import numpy
    from numpy.testing.utils import get_file
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing.utils import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
    from numpy.testing import get_filesystem_input
