def _import ( ) : return _import ( io.BytesIO ( ) )
import io.BytesIO
import io.BytesIO
import io.BytesIO
import numpy as np
import struct
import struct
import numpy as np
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
import struct
from struct
import struct
import struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
import struct
from struct
from struct SPACETOKEN import SPACETOKEN struct ; SPACETOKEN struct ; SPACETOKEN < i > e ; SPACETOKEN struct SPACETOKEN < b > ( ) < / i > ; SPACETOKEN < / b > SPACETOKEN < / a > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / a > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / a > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / a > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / a > SPACETOKEN < / b > SPACETOKEN < / b > SPACETOKEN < / b >
