def _import ( ) :
    from locale import get_locale
    from time import sleep
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from locale import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getgetlocale
    from decimal import getintsline
    from locale import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getgetlocale
    from decimal import getlocale
    from decimal import getgetlocale
    from decimal import getgetlocale
    from decimal import getgetgetintsline
    from locale import getlocale
    from decimal import getlocale
    from decimal import getgetlocale
    from decimal import getgetintsline
    from locale import getlocale
    from decimal import getlocale
    from decimal import getlocale
    from decimal import getgetlocale
    from locale import getgetgetgetlocale
    from locale import getgetgetgetlocallocale
    from locale import getgetgetlocale
    from locale import getgetgetpreferredencoding
    from locale import getgetgetpreferredencoding
    from locale import getgetpreferredencoding
    from locale import getgetgetlocale
    from locale import getgetgetlocale
    from locale import getgetgetlocallocale
    from locale import getgetgetcommonlocale
    from locale import getgetlocale
    from locale import getgetcommonlocale
    from getcommoncommoncommonlocale import getcommoncommoncommoncommonkeys
    from locale import getcommoncommoncommoncommoncommoncommonkeys
