def import _readline
from sys import stdout
from os import urandom
from random import randint
from os import urandom
from os import urandom
from os import urandom
from io import StringIO
from os.path import expanduser
from os.environ import ''
from os.environ import ''
from os.environ import ''
from os.environ import environ
from os.environ import ''
from os.environ import environ
from os.chdir
class Main ( object ) :
    def __init__ ( self ) :
        from os import urandom
        from os import urandom
        from io import StringIO
        from os.urandom import urandom
        from os.path import expanduser
        from os.environ import ''
        from os import urandom
        from os import urandom
        from os.urandom import randint
        from os.urandom import urandom
        from os.path import expanduser
        from os.environ import ''
        from os.environ import environ
        from os.environ import get
        from os.path import expanduser
        from os.path import join
        from os.path import expanduser
        from os.path import join
        from os.path import expanduser
        from os.path import exists
        from os.path import expanduser
        from os.path import join
        from os.path import expanduser
        from os.path import join
        from os.path import expanduser
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.path import exists
        from os.nonexistfile import exists
        from os.path import exists
        from os.nonexistfile import exists
        exists = exists
