def main ( ) :
    import sys
    import random
    from random import randint
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import randrange
    from random import choice
    from random import randrange
    from random import choice
    from random import randrange
    from random import choice
    from random import choice
    from random import randrange
    from random import choice
    from random import choice
    from random import randrange
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import randrange
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import randint
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
