def _import ( ) :
    from sys import stdin , stdout
    from os import getenv
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import abspath
    from os.environ import environ
    from os.chdir import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os import chdir
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os import chdir
    from os.path import join
    from os import chdir
    from os import getcwd
    from os.path import join
    from os import chdir
    from os.path import join
    from os import chdir
    from os.path import join
    from os import chdir
    from os.path import join
    from os import chdir
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import isfile
    from os.path import join
    from os.path import join
    from os.path import dirname , join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import isfile
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import isfile
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import isfile
    from os.path import join
    from os.path import join
    from os.walk import join
    from os.path import join
    from os.path import join
    from os.walk import join
    from os.path import join
    from os.path import join
