def _solve ( x , n ) : return x
import Queue
from collections import deque
from collections import deque
from collections import deque
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
