def _import ( ) : return sys.stdin.read ( )
import string
import tokenize
import tokenize
import function
class Main ( object ) :
    def __init__ ( self , f ) :
        self.N , self.M = f.readline ( )
        self.X , self.Y = f.readline ( )
        self.A = self.A
        self.B = self.A
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
        self.C = f.readline ( )
