def _import ( ) : return sys.stdin.read ( )
import input_reader
import input_reader
import input_writer
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_reader
import input_writer
import input_reader
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_writer
import input_reader
import input_writer
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_reader
import input_writer
import input_writer
