def main ( ) :
    import sys
    from itertools import isPrime
    from math import sqrt
    from math import sin
    from math import cos
    from math import sqrt
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import cos
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
    from math import sin
