def main ( ) :
    import sys
    from random import randint
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import max
    from time import max
    from time import min
    from time import max
    from time import max
    from time import min
    from time import max
    from time import max
    from time import min
    from time import max
    from time import max
    from time import min
    from time import max
    from time import max
    from time import min
    from time import max
    from time import max
    from time import min
    from time import max
    from time import max
    from time import min
    from time import max
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import min
    from time import max
    from time import min
    from time import min
    from time import max
    from time import min
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import max
    from time import min
    from time import min
