def _import ( ) :
    import time
    import sys
    import os
    import sys
    import os
    import sys
    import time
    import random
    import random
    import random
    import random
    import sys
    class C ( ) :
        global THREADS
        THREADS = 1
        NAME = 'c-large'
        def read_data ( ) :
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            global stdout
            stdout = stdout
            stdout = stdout
            stdout = stdout
            stdout = stdout
            stdout = stdout
            stdout = stdout
            stdout = stdout
            stdout = stdout
            stdout = stdout
    