def import struct
from sys import stdin
from struct
from struct import Struct
from struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct
class Struct :
    def __init__ ( self ) :
        self.Struct = Struct
