def main ( ) :
    import sys
    from math import fabs
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
