def main ( ) :
    from random import randint
    from itertools import chain
    from itertools import chain
    from random import choice
    from itertools import chain
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from from random import shuffle
    from from from from from .import shuffle
    import shuffle
    from from from .import shuffle
    from .import shuffle
