def _ _ main _ _ ( ) : return sys.stdin
import io
import os
import sys
import os
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer
import integer

import string
import string
import string

