def import _main
from os.path import join
from os import urandom
from os import urandom
from os import urandom
from os.path import expanduser
from os.path import join
from os.path import expanduser
from os.path import join
from os.path import join
from os.path import join
from os import urandom
from os.path import join
from os.path import expanduser
from os.path import join
from os.path import join
from os import path as path_join
from os.path import expanduser
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import exists
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import join
from os.path import exists
from os.path import join
from os.path import join
from os.path import exists
from os.path import join
from os.path import join
from os.path import join
from os.path import exists
from os.path import join
from os.path import join
from os.path import exists
from os.path import join
from os.path import join
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import join
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import join
print ( join ( dir ( join ( dir ( dir ( join ( dir ( dir ( join ( dir ( dir ( join ( dir ( dir ( join ( dir ( ) )