def _ _ new _ _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
def _ ( ) : return
