def _import ( * args , ** kwargs ) :
    from io import StringIO
    from random import randint
    from random import randint
    from sys import stdin
    from sys import stdout
    from sys import stderr
    from os.path import join
    from os import getenv
    from os import getcwd
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
