def __main__ ( ) :
    from string import ascii_lowercase
    from collections import defaultdict
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_uppercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
    from string import ascii_lowercase
