def import import sys , StringIO , ETrBBnsformBBtion
from io import BytesIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import BytesIO
from io import StringIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import ETrBBnsformBBtion
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
import SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.SeqIO.EOF
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
import BytesIO
from io import BytesIO
from io import BytesIO
