def import java.io.StringIO
import sys
from java.io import StringIO
from java.util import StringDecoder
from java.io import StringIO
from java.util import safe_decode
from java.io import StringIO
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
from java.util import safe_decode
