def _gen_binomial_coefficients ( n , module ) :
    import sys
    import io
    import io
    import io
    import itertools
    import io
    import io
    import codecs
    import io
    import codecs
    import io
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    import codecs
    codecs
    import codecs
    import codecs
    import codecs
    
    import codecs
    
    import codecs
    
    import codecs
    
    import codecs
    
    
    import codecs
    
