def _solve_small_n ( n , W , v ) :
    import sys
    import os
    import os.path
    import sys
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
    import napsack.input_error
