def _solve_2 ( ) :
    import os
    from math import ceil
    from os.path import join
    from os import curdir
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os import curdir
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os.path import abspath
    from os.path import join
    from os import curdir
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import join
    from os.path import exists
