def _main ( ) :
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os.path import join
    from os.path import join
    from os import getenv
    from os.path import join
    from os import getenv
    from os.path import join
    from os import getenv
    from os import getenv
    from os import getenv
    from os.path import join
    from os import getenv
    from os.path import join
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( ) ) ) ) ) ) ) ) ) ) ) )
    if getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
    if getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv ( getenv (