def lab6zp ( ) :
    import sys
    from itertools import repeat
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
    from nltk.corpus import brown
