def main ( ) :
    import sys
    from random import randint
    from time import sleep
    from math import sin , cos , cos , log
    from os import urandom
    from os import urandom
    from os import urandom
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import choice
    from random import random
    from random import randint
    from random import choice
    from random import random
    from random import randint
    from random import randint
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    from random import uniform
    # from random import uniform
