def _import ( ) : return sys.stdin.read ( )
import readline
import readline
import readline
import readline
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
import readline.parse_file
readline.parse_file ( readline.strip ( ) )
