def import _readline
import sys
from io import BytesIO
from io import BytesIO
from io import BytesIO
import readline
from io import BytesIO
import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import BytesIO
from io import readline
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import readline
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
