def import readline
import sys
from io import StringIO
from io import BytesIO
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
from py2exe import py2exe
