def _ _ main _ _ ( ) : return sys.argv [ 1 ]
from waflib import Logs
from waflib import Task
from waflib import Task
from waflib.TaskGen import TaskGen
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
from waflib.TaskGen import Task
