def _solve ( N , P , R , Q ) :
    from scipy.sparse import csc_matrix
    from scipy.sparse import csc_matrix
    from scipy.sparse import csc_matrix
    from scipy.sparse import csc_matrix
    from scipy.sparse import csc_matrix
    from scipy.sparse import csc_matrix
    from scipy.sparse import csc_matrix
    from scipy.sparse import csc_matrix
    from scipy.sparse import csc_matrix
    from scipy.sparse.csr import csr_matrix
    from scipy.sparse.linalg import solve
    from scipy.sparse.csr import csr_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.csr import csr_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csr_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import solve
    from scipy.sparse.csr import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import solve
    from scipy.sparse.csr import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import solve
    from scipy.sparse.csr import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    from scipy.sparse.linalg import csc_matrix
    return csc_matrix ( csc_matrix ( N ) )