def _import ( ) : return sys.stdin.read ( )
def _import ( s ) : return sys.stdout.write ( s )
def _import ( s ) : return sys.stdin.read ( )
def _import ( s ) : return sys.stdout.write ( s )
def _import ( s ) : return sys.stdin.read ( )
def _import ( s ) : return sys.stdout.write ( s )
def _import ( s ) : return sys.stdin.read ( )
def _import ( s ) : return sys.stdout.write ( s )
def _import ( s ) : return sys.stdin.read ( )
def _import ( s ) : return sys.stdout.write ( s )
def _import ( s ) : return sys.stdin.read ( )
def _import ( s ) : return sys.stdin.read ( )
def _import ( s ) : return sys.stdout.write ( s )
def _import ( s ) :
    while not s.startswith ( ' ' ) :
        s = s [ 1 : ]
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    s = _import ( s )
    return s
