def main ( ) :
    import sys
    from numpy import arange
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import index2
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
    from numpy.core import min
    from numpy.core import max
