def gcj ( ) :
    import os
    import sys
    from os import chdir
    from os import environ
    from os.path import join
    from os import chdir
    from os import sep
    from os.path import join
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from string import ascii_letters
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import lower
    from string import upper
    from string import upper
    from string import upper
    from string import upper
