def _import ( ) :
    import sys
    import float
    import int
    import long
    import sys
    import struct
    import shlex
    import sys
    import termios
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import sys
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import struct
    import sys
    import struct
    import struct
    import sys
    import struct
    import sys
    import struct
    import sys
    import struct
    import struct
    import sys
    import struct
    import sys
    import struct
    import struct
    import sys
    import struct
    import sys
    import struct
    import struct
    import sys
    import struct
    import struct
    import sys
    import struct
    import struct
    import sys
    import struct
    import struct
    import sys
    import struct
    import struct
    import sys
    import struct
    import struct
    import struct
    import sys
    import struct
    import struct
    import struct
    import sys
