static final String getTestName ( String [ ] args ) {
  /* get the cavePositions */
  final Set < Integer > cavePositions = new THashSet < Integer > ( ) ;
  final Iterator < String > it = new Iterator < String > ( ) {
    String [ ] cars ;
    int i ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    int [ ] cars ;
    cars = it . next ( ) ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 2 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 2 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 2 ] ;
    cars = cars [ 3 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 2 ] ;
    cars = cars [ 3 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 2 ] ;
    cars = cars [ 3 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [ 2 ] ;
    cars = cars [ 3 ] ;
    cars = cars [ 3 ] ;
    cars = cars [ 0 ] ;
    cars = cars [ 1 ] ;
    cars = cars [