def _import ( ) :
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
    from pycket.interpreter import readline
