def _import ( ) : return _import ( )
def _import ( ) : return _import ( )
def _import ( ) : return _import ( )
import collections
import collections
import Queue
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
import collections
class K
class T
class C :
    import collections
