def _solve_test ( ) :
    from os import urandom
    from os import fdopen
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os import sep
    from os import path
    from os import exists
    from os import exists
    from os import sep
    from os import path
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import path
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import path
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import path
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
    from os import exists
