def gcj.gcj2017.round1 ( ) :
    import sys
    import math
    import math
    import math
    import os
    import sys
    import os
    import math
    import os
    import sys
    import math
    import math
    import random
    import math
    import sys
    import math
    import sys
    import math
    import sys
    import math
    import sys
    import math
    import time
    import time
    import time
    import time
    import time
    import sys
    import math
    import math
    import traceback
    import math
    import math
    import sys
    import math
    import math
    import sys
    import math
    import math
    import math
    import sys
    import math
    import math
    import math
    import sys
    import math
    import math
    import math
    import math
    import sys
    import math
    import math
    import sys
    import math
    import math
    import sys
    import math
    import sys
    import math
    import math
    import sys
    import math
    import math
    import math
    import math
    import sys
    import math
    import math
    import math
    import sys
    import math
    import math
    import sys
    import math
    import math
    import math
    import math
    import math
    import sys
    import math
    import math
    import math
    import math
    import math
    import math
    import sys
    import math
    import math
    import math
    import math
    import sys
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    import math
    # sys.exit()
