def main ( ) : return
import sys
import os
import random
import time
import random
import sys
class MainC ( ) :
    def __init__ ( self ) :
        self.stdin = open ( 'input.txt' , 'w' )
        self.stdout = open ( 'output.txt' , 'w' )
        self.stdin.write ( 'Case #%d: ' % ( t + 1 ) )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
        self.stdin.close ( )
