def test_D ( ) :
    from sympy.utilities.iterables import iterables
    from sympy.printing.latex import latex
    from sympy.printing.latex import Printer
    from sympy.printing.printing import latex
    from sympy.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    from sympy.core.printing.latex import Printer
    from sympy.core.printing.printing import Printer
    print ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer ( Printer , Printer ( Printer , Printer ( Printer , Printer ( Printer , Printer , Printer , Printer ( Printer ( Printer , Printer.Printer ) , Printer ( Printer ( Printer ( Printer ) ) ) )