def _import ( ) :
    import sys
    import random
    import math
    import random
    import string
    import string
    import string
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import sys
    import struct
    import string
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import sys
    import struct
    import struct
    import string
    import struct
    import math
    import string
    import string
    import random
    import string
    import random
    import struct
    import struct
    import struct
    import struct
    import struct
    import string
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
    import struct
