def _main ( ) :
    from sys import stdin , stdout
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os.write import urandom
    from os import urandom
    from os.write import urandom
    from os import urandom
    from os import urandom
    from os.write import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.urandom import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.urandom import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.urandom import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
