def _import ( ) :
    from sys import stdin as PIPE
    from os import urandom
    from os import system , randrange
    from os.path import expanduser
    from os.path import expanduser
    from os.path import expanduser
    from os.path import join
    from os.path import abspath
    from os.path import abspath
    from os.path import abspath
    from os.path import abspath
    from os.path import abspath
    from os.path import abspath
    from os import urandom
    from random import randint
    from random import random
    from os import urandom
    from os import urandom
    from os import urandom
    from random import random
    from os import urandom
    from os import urandom
    from os import urandom
    from random import random
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from random import randint
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
