def _import ( ) :
    from os import getenv
    from os import getenv
    from os import open
    from os import getenv
    from os import getenv
    from os.path import join
    from os import getenv
    from os.path import join
    from os import sep
    from os import chdir
    from random import randint
    from random import random
    from itertools import product
    from itertools import chain
    from os import path as stream
    from os.path import isfile
    from os import sep
    from os import sep
    from os import chdir
    from random import randint
    from random import random
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from random import randint
    from random import randint
    from random import randint
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from random import randint
    from random import randint
    from random import randint
    from time import time
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from time import time
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import random
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    cwd = getcwd ( )
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.chdir ( getcwd ( ) )
    print ( "" , join ( dirname ( abspath ( join ( dirname ( abspath ( __file__ ) ) ) ) ) for dirname ( abspath ( abspath ( __file__ ) )