def _ _ main _ _ ( ) : return
def _ ( cur , count ) : return [ nextLong ( ) ]
def _ ( cur , count ) : return [ nextLong ( ) ]
def _ ( cur , count ) : return [ nextLong ( ) ]
def _ ( cur , count ) : return [ nextLong ( ) ]
def _ ( cur , count ) : return [ nextLong ( ) ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur , count ) : return [ ]
def _ ( cur