def _import ( stream ) : return stream
import sys
from os import urandom
from os import fdopen
from os import fdopen
from os import fdopen
from os.path import join
from os import sep
from os import fdopen
from os.path import join
from os import sep
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import path as fdopen
