def import _readline
from sys import stdin
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import BytesIO
from io import readline
from io import BytesIO
from io import readline
from io import readline
from io import readline
from io import BytesIO
from io import readline
