def _import ( ) :
    from sys import stdin as stream
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct
    from struct import Struct
    from struct import Struct
    from struct
    from struct import Struct
    from struct import Struct
    from struct
