def _import ( ) :
    from numpy import pi
    from numpy.core import zeros
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
    from numpy.core import O
