def _import ( ) : return sys.stdin.read ( )
import io
import sys
import struct
import time
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
from time import sleep
sleep = sleep
sleep ( sleep ( sleep ( sleep ( sleep ( sleep ) ) ) ) )
