def main ( ) :
    import sys
    import random
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
    from numpy.core import zeros
