def main ( ) :
    import sys
    from time import sleep
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from math import radians
    from