def _import ( ) : return _import ( )
from time import sleep
from time import sleep
from sys import maxsize
from sys import stdout , stderr
from struct import calcsize
from struct import Struct , calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import calcsize
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import calcsize
from struct import calcsize
from struct import calcsize
from struct import calcsize
from struct import calcsize
from struct import calcsize
from struct import calcsize
from struct import calcsize
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import Struct
from struct import calcsize
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import calcsize
from struct
