def _import ( ) : return next ( )
import sys
import termios
import sys
import struct
import termios
import sys
class Main ( object ) :
    def __init__ ( self ) :
        termios.tcsetattr ( sys.stdin , termios.TCSADRAIN , self )
        self.stdin = sys.stdin
        self.stdout = sys.stdout
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdin.isatty ( )
        self.stdout.isatty ( )
