def _main ( * args ) : return _main ( * args )
def _main ( * args ) : return _main ( * args )
def _MOD ( ) : return _MOD ( 1e9 ) + 7
def _encode ( * args ) : return _main ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_decode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_decode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode ( * args ) : return _fig_encode ( * args )
def _fig_encode (