def _ _ new _ _ ( ) : return
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
class _Main ( object ) : pass
