def _ _ init _ _ ( ) : return 0
def __init__ ( self , n ) : return - n if n < int ( n ) else n
def __init__ ( self , v ) : return v
def __init__ ( self , n ) : return n
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
def __init__ ( self , v ) : return v
