public static String input ( ) {
  String s = input ( ) ;
  String ans = "" ;
  switch ( s ) {
    case "WBWBWWBWBWBWBWWBWBW" : ans = "Do" ;
    break ;
    case "WBWWBWBWBWBWBWWBWBW" : ans = "Re" ;
    break ;
    case "WWBWBWBWBWBWBWBWWBWBWBW" : ans = "Mi" ;
    break ;
    case "WBWBWBWBWBWBWBWW" : ans = "Fa" ;
    break ;
    case "WBWBWBWBWBWBWBWBWBWW" : ans = "So" ;
    break ;
    case "WBWWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWBWW" " ) ; break ; } return ans ; }