def import readline , eat
import sys
import os
import sys
class Solution ( object ) :
    def __init__ ( self ) :
        self.f = 'B-large'
        self.stdin = open ( 'stdin' , 'w' )
        self.stdout = open ( 'stdout' , 'w' )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdin.readline ( )
        self.stdout ( )
    