def import import sys , string , traceback
from os import popen
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
from os import environ
