def _import ( ) : return sys.stdin.read ( 1024 )
import io
import sys
import struct
import sys
import termios
from struct import Struct
from termios import Struct
from termios import Struct
from struct import Struct
from termios import Struct
from struct import Struct
from termios import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct
