def _import ( ) :
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os import getenv
    from os.path import join
    from os.path import join
    from os.path import join
    from os import sep
    from os.path import join
    from os import sep
    from os.path import join
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import chdir
    from os import sep
    from os import chdir
    from os import sep
    from os import chdir
    from os import chdir
    from os import sep
    from os import chdir
    from os import chdir
    from os import sep
    from os import chdir
    from os import chdir
    from os import sep
    from os import chdir
    from os import chdir
    from os import chdir
    from os import sep
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os import chdir
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os.chdir
    try :
        chdir ( getcwd ( ) )
    except :
        print ( )
