def main ( ) :
    import sys
    from random import randint
    from time import sleep
    from time import sleep
    from os.path import join
    from os import path
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os.path import join
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os.path import join
    from os.path import join
    from os import urandom
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.remove import remove
