def _import ( ) :
    from sys import stdin as stream
    from binascii import hexlify
    from binascii import b2a_uu
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
    from binascii import unhexlify
