def _import ( ) : return _import ( )
def _import ( to ) : return _import ( to )
def _import ( * os ) : return sys.stderr.write ( deeprepr ( os ) )
def _import ( * args ) :
    try :
        sys.stdin.write ( open ( args [ 0 ] + ".in" , "r" ).read ( ) )
    except :
        pass
    else :
        s = [ ]
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
        s.append ( s.pop ( 0 ) )
