def _ _ main _ _ ( ) :
    import sys
    class cross ( QUAD ) :
        def __init__ ( self ) :
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
            self.T = [ ]
    print ( "Case #%d: %s" % ( self.T [ 0 ] , self.T [ 0 ] ) )
