def _import ( ) :
    import math
    import numpy as np
    import numpy as np
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
    import numpy.fft as fft
