def _import ( ) : return sys.stdout.write
from .utils import is_space , read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
from .utils import read_bytes
