def import import os , get_max , diff = None ) :
    from random import random
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_max
    from genomicode import get_min
    from genomicode import get_max
    from genomicode import get_max
