def pl.helman.codejam.dancing ( ) :
    import os
    from os import path
    from os import rename
    from os import getcwd
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os import getcwd
    from os import chdir
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import chdir
    from os.path import join
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import chdir
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
