def _import ( ) :
    import time
    import math
    import os
    import os
    import time
    import math
    import time
    import math
    import time
    import math
    import time
    import time
    import math
    import time
    import time
    import math
    import time
    import time
    import math
    import time
    import time
    import time
    import math
    import time
    import time
    import time
    import time
    import time
    import time
    import math
    import time
    import time
    import time
    import time
    import time
    import time
    import math
    import time
    import time
    import time
    import time
    import time
    import time
    import math
    import time
    import time
    import time
    import math
    import time
    import time
    import time
    import time
    import time
    import math
    import time
    import time
    import time
    import math
    import time
    import time
    import time
    import math
    import time
    import time
    import math
    import time
    import math
    import time
    import math
    import time
    import math
    import time
    import time
    import math
    import time
    import math
    import time
    import time
    import math
    import time
    import math
    import time
    import math
    import time
    import math
    import time
    import math
    import time
    import math
    import math
    import time
    import math
    import time
    import math
    import math
    import time
    import math
    import math
    import time
    import math
    import math
    import time
    import math
    import math
    import time
    import math
    import math
    import time
    import math
    import math
    import time
    import math
    import math
    import time
    time
    import math
    import math
    import time
    time
    import math
    import math
    import math
    import time
    time
    import math
    import math
    time
    import math
    # print()
