def main ( ) :
    def solve ( ) :
        n = ni ( )
        m = ni ( )
        from [ 0 ] import int
        from [ 0 ] import readline
        from [ 1 ] import readline
        from [ 2 ] import readline
        from [ 3 ] import readline
        from [ 4 ] import readline
        from [ 6 ] import readline
        from [ 8 ] import readline
        from [ 7 ] import readline
        from [ 8 ] import readline
        from [ 9 ] import readline
        from [ 8 ] import readline
        from [ 9 ] import readline
        from [ 10 ] import readline
        from [ 11 ] import readline
        from [ 12 ] import readline
        from [ 13 ] import readline
        from [ 14 ] import readline
        from [ 15 ] import readline
        from [ 16 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 24 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
        from [ 17 ] import readline
    