def _import ( ) : return 1 if sys.version_info [ 0 ] >= 3 else - 1
def _import ( x , d ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return float ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return float ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return float ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return float ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return float ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return float ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return float ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return int ( x )
def _import ( x ) : return x
