def import _dfs_edges
from os import getenv
from os import chdir
from os import environ
from os import environ
from os import chdir
from os import environ
from os import chdir
from os import environ
from os import chdir
from os import environ
from os import chdir
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
from collections import defaultdict
