def main ( ) :
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
    from decimal import Decimal
