def import java.io.StringIO
from java.lang import Character
from java.lang import Integer
from java.lang import Character
from java.util import FastScanner , TreeMap
from java.util import StringDecoder
from java.lang import String
from java.lang import Integer
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Float
from java.lang import Character
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Character
from java.lang import String
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Character
from java.lang import Character
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Integer
from java.lang import Character
from java.lang import Character
