def import _readline
from sys import stdin , stdout
from sys import stderr
from os import urandom
from os import urandom
from random import randint
from os import urandom
from os import urandom
from os import urandom
from io import BytesIO
from os import urandom
from io import BytesIO
from os import urandom
from io import BytesIO
from os import urandom
from io import BytesIO
from os import urandom
from io import BytesIO
from os import urandom
from io import BytesIO
from random import randint
from random import randint
from random import randint
from io import BytesIO
from os import urandom
from io import BytesIO
from os import urandom
from io import BytesIO
from random import randint
from random import randint
from io import BytesIO
from os import urandom
from io import BytesIO
from os import urandom
from io import BytesIO
from random import randint
from io import BytesIO
from os import urandom
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from os import urandom
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from os import urandom
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from os import urandom
import pyb
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from io import BytesIO
from os import urandom
from io import BytesIO
from io import BytesIO
from io import BytesIO
from os import urandom
from io import BytesIO
from os import urandom
from os import urandom
from io import BytesIO
from os import urandom
from io import BytesIO
from os import urandom
from os import urandom
from io import BytesIO
from os import urandom
from os import urandom
from io import BytesIO
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from io import BytesIO
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
