def import __main__
class Main ( object ) :
    def __init__ ( self ) :
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'ch' )
        self.po = __main__.get ( 'o' )
        self.po = __main__.get ( 'k' )
        self.po = __main__.get ( 'u' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__.get ( 'po' )
        self.po = __main__