def import import sys
from os.path import getsize
from os import urandom
from random import randint
from sys import stdin
from os.path import expanduser
from os.path import join
from os import urandom
from os.path import join
from os.path import expanduser
from os.path import join
from os.path import join
from os.path import join
from os import sep
from os.path import join
from os import sep
from os.path import join
from os import sep
from os import chdir
from os.path import join
from os.path import join
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import join
from os.exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import join
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.import exists
from os.path import exists
from os.path import exists
