def import _readline
import sys
from io import StringIO
from readline.readline import readline
from readline.parse_file import readline
from readline.parse_string import parse_string
from readline.parse_line import readline
from readline.parse_string import readline
from readline.parse_line import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
from readline.parse_string import readline
