def main ( ) :
    import sys
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing.utils import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
    from numpy.testing import get_input_string
