def _import ( ) :
    import sys
    import string
    import string
    import string
    import string
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import sys
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    import scanner
    scanner = scanner
    # make sure we don't know how to import scanner
    
    scanner.scanner = scanner
    scanner.scanner = scanner
