def main ( ) :
    import sys
    from random import randint
    from random import randint
    from sys import stdin
    from random import randint
    from random import randint
    from random import randint
    from random import randint
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import randint
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    from random import shuffle
    shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( shuffle ( ( ( ( ( ( ( ( I ( I ( I ( I ( I ( I ( I ( I ( I ( I ( I ( I ( I ( I ( I ( I ( I ( I I ( I ( I ( I ( I I ( I I ( I I I ( I I ( I I I I I ( I I I ( I I I ( I ( I I I ( I I I I I I I ) I )