def _main ( args ) :
    from time import time , raw_input
    from io import BytesIO
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ) ) ) ) ) ) ) )
    from time import sleep
    sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ( sleep ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )
