def import import readline
import sys
import os
import getopt
import time
from time import sleep
from os.environ import Env
from os.environ import Env
from os.name import environ
from os.environ import Env
from os.chdir ( Env.PATH )
from os import chdir
from os.environ import Env
from os.environ import Env
from os.chdir ( Env.PATH )
from os import chdir
from os.environ import Env
from os.path import abspath
from os.environ import expanduser
from os.path import join
from os import environ
from os.path import abspath
from os.environ import chdir
from os.path import expanduser
from os.path import join
from os import path
from os import chdir
from os.path import abspath
from os.path import join
from os import getcwd
from os.path import join
from os import chdir
from os.path import expanduser
from os.path import join
from os import path
from os import chdir
from os.path import join
from os.path import expanduser
from os.path import join
from os import path
from os.path import join
from os import chdir
from os.path import expanduser
from os.path import join
from os.path import normpath
from os.path import join
from os.path import expanduser
from os.path import join
from os.path import join
from os.path import dirname
from os.walk import walk
from os.path import basename
from os.path import normpath
from os.path import join
from os.path import dirname
from os.walk import walk
from os.path import normpath
from os.path import join
from os.path import normpath
from os.walk import walk
from os.path import dirname
from os.path import basename
from os.path import join
from os.path import dirname
from os.walk import normpath
from os.path import join
from os.path import normpath
from os.path import join
from os.path import dirname
from os.walk import normpath
from os.path import dirname
from os.walk import normpath
from os.path import dirname
from os.walk import normpath
