def import import StringIO
from itertools import chain
from StringIO import StringIO
from itertools import chain
from itertools import chain
from pyamf import TaskB
from pyamf import StringIO
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
from pyamf import TaskBase
