def _import ( ) : return _import ( float , int , long , sys.exit , _import )
from itertools import repeat
from itertools import chain
from os import urandom
from io import BytesIO
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import remove
