def pycompany ( ) :
    import os
    import sys
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
    from pycompany.utils import redirect
