def import import sys , exit
import string
import sys
import string
import math
import string
import sys
import string
import sys
import string
import string
import sys
import string
import string
import string
import sys
import string
import string
import string
import sys
import string
import string
import string
import sys
import string
import string
import sys
import string
import string
import sys
import string
import string
import sys
import string
import string
import sys
import string
import string
import sys
from string import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
import make_ascii
