def _ _ main _ _ ( ) : return
def main ( ) : return
def main ( ) : return
def dfs2 ( a , b , leftover ) : return [ a ] [ b ] [ c ] [ leftover ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def write ( out , test_number ) : return [ ]
def dfs ( a ,