def _compose ( a , b ) : return a
def _compose ( a , b ) : return a [ b ]
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return a
def _compose ( a , b ) : return b
def _compose ( a , b ) : return a
def _compose ( a , b ) : return b
def _compose ( a , b ) : return a
