def import readline
from sys import stdin
from io import BytesIO
from struct import calcsize
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct import Struct
from struct
class Struct ( Struct ) :
    def __init__ ( self ) :
        self.Struct = Struct
