def import _raw_input
from StringIO import StringIO
from io import BytesIO
from io import BufferedReader
from io import BufferedWriter
from io import StringIO
from io import BufferedReader
from io import BufferedReader
from io import BufferedWriter
from io import StringIO
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedWriter
from io import StringIO
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedWriter
from io import StringIO
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import StringIO
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import StringIO
from io import BufferedReader
from io import BufferedReader
from io import BufferedReader
from io import StringIO
from io import BufferedReader
