def _main ( ) :
    from math import sin , cos , log
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path
    from os import path as path
    from os import path
    from os import path as path
    from os import path
    from os import path as path
    from os import path as path
    from os import path as path
    from from os import path as path
