def _import ( ) :
    from math import pow , sin , cos , log
    from os import path
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from time import time
    from random import randint
    from random import random
    from time import time as time
    from time import sleep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from time import sleep
    from time import sleep
    from time import sleep
    from time import sleep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
    from os import sep
