def import import sys , StringIO
from os import urandom
from io import BytesIO
from os import urandom
from io import BytesIO
from os import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
from io import fdopen
