def contest.codejam ( ) :
    import sys
    import os
    import subprocess
    import subprocess
    import subprocess
    import sys
    import subprocess
    import random
    import random
    import string
    import string
    import random
    import string
    import random
    import string
    import random
    import math
    import random
    import random
    import math
    import random
    import random
    import math
    import random
    import random
    import random
    import sys
    import subprocess
    import subprocess
    import subprocess
    import subprocess
    import subprocess
    import time
    import time
    import time
    import time
    import random
    import string
    import random
    import sys
    import subprocess
    import subprocess
    import subprocess
    import os
    import sys
    import os
    import subprocess
    import tempfile
    import os
    import sys
    import os
    import tempfile
    import time
    import time
    import random
    import random
    import math
    import random
    import math
    import random
    import sys
    import math
    import random
    import sys
    import time
    import time
    import time
    import random
    import sys
    import subprocess
    import time
    import time
    import random
    import sys
    import math
    import random
    import string
    import string
    import random
    import sys
    import os
    import os
    import sys
    import os
    import subprocess
    import subprocess
    import subprocess
    import subprocess
    import os
    import os
    import sys
    import os
    import os
    import sys
    import os
    import string
    import random
    import random
    import sys
    import random
    import string
    import random
    import sys
    import random
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import os
    import sys
    import os
    import os
    import sys
    import string
    import random
    import random
    # from sys
