def win32com ( ) : return
import win32com
import win32com
import win32com.client
import win32com.client
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
import win32com.client.Dispatch
