def _readline ( ) : return _readline ( )
class _readline ( iter ) :
    def __iter__ ( iterable ) : return iter
    def next ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( iterable ) : return iter
    def __iter__ ( ) : return iter
    def __iter__ ( ) : return iter
