def main ( ) :
    import sys
    from collections import defaultdict
    from os.path import join
    from os import path
    from os import getcwd
    from os.path import join
    from os import path
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os.path import join
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os import getcwd
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import dirname
    from os.path import join
    from os.path import join
