def main ( ) :
    import sys
    import os
    from numpy import zeros , zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
    from numpy import zeros
