def test_C ( ) :
    import random
    from os import urandom
    from random import randint
    from os import urandom
    from os import fdopen
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.path import exists
    from os.exists import exists
    from os.path import exists
    from os.remove import exists
    from os.remove import exists
