def _main ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr ( * o ) : return o
def _tr (