def _import ( * os ) : return sys.stderr.write ( deeprepr ( os ) )
class Main ( object ) :
    MOD = long ( 1e9 ) + 7
    def __init__ ( self , * os ) :
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
        self._import ( * os )
