def _import ( * args ) : return _import ( * args )
def _import ( out ) : return out
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def MOD ( n ) : return _import ( n )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args ) : return _import ( * args )
def _import ( * args )