def _import ( ) : return open ( '/' ).read ( )
import sys
import os
import math
import os
import sys
import os
import sys
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import integer
import long
import integer
import float
import string
import string
import decimal
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import string
import sys
import string
import string
import sys
import string
import integer
import long
import float
import string
import string
import decimal
import string
import string
import sys
import string
import string
import sys
import string
import sys
import string
import sys
import string
import sys
import string
import sys
import string
import sys
import string
import sys
import string
import sys
import string
import sys
import string
import sys
class A ( object ) :
    def __repr__ ( self ) :
        return '%s%s%s' % ( string.__repr__ ( self ) , string.__repr__ ( self ) , string.__repr__ ( self ) )
