def _import ( ) : return sys.stdin
import getopt
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
from os import fdopen
