def test_solve ( ) :
    from random import randint
    from numpy import random
    from numpy import array
    from random import uniform
    from numpy import random
    from numpy import array
    from random import uniform
    from numpy import random
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing.utils import solve
    from numpy.testing import solve
    from numpy.testing.utils import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.utils import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
    from numpy.testing import solve
