def import input_reader
from sys import stdin , stdout
from sys import stderr
from os import urandom
from random import randint
from random import random
from math import pow
from random import random as randrange
from math import log
from six import StringIO
from six.moves import StringIO
from six.moves import StringIO
from six.moves import StringIO
from six.moves import StringIO
from six.moves import builtins
from six.moves import configparser
from six.moves import StringIO
from six.moves import configparser
from six.moves import StringIO
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import StringIO
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
from six.moves import configparser
