def _import ( ) : return int ( next ( ) )
def _import ( ) : return float ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return float ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return float ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return float ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) : return int ( next ( ) )
def _import ( ) :
def _import ( ) :
    import sys
    import os
    import string
    os.remove ( '' )
