def main ( args ) :
    from numpy import arange
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
    from numpy.core import fcode
