def import readline , stream
from io import BytesIO
from codecs import BOM_UTF8 , BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from io import BOM_UTF8
from codecs import BOM_UTF8
from io import BOM_UTF8
from codecs import BOM_UTF8
from io import BOM_UTF8
