static final String solve ( ) {
  final rl = new rl ( ) ;
  final StringBuilder buf = new StringBuilder ( ) ;
  buf . append ( str ) . append ( " " ) ;
  buf . append ( mx ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " " ) ;
  buf . append ( " ▁