def test_solve_a ( ) :
    from sympy.abc import x
    class A ( object ) :
        def __init__ ( self ) :
            self.solved_a = solve_a ( )
        def solved_b ( self ) :
            with open ( "a" , "r" ) as f :
                num_n = f.read ( )
                if num_n % 2 == 0 :
                    print ( num_n )
                else :
                    print ( num_n * 2 )
                print ( "" )
        def solved_c ( self ) :
            with open ( "c" , "r" ) as f :
                num_n = f.read ( )
            print ( "" )
        def solved_d ( self ) :
            with open ( "d" , "r" ) as f :
                num_n = f.read ( )
            print ( "" )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
    A ( )
