def _import ( * args ) : return _import ( * args )
class Main :
    def __init__ ( self ) :
        self.stream = sys.stdin
        self.stream = sys.stdout
        self.stream.seek ( 0 )
        self.stream.seek ( 0 )
        self.stream.read ( 1 )
    def read ( self ) :
        self.stream.seek ( 0 )
        self.stream.read ( 1 )
        self.stream.seek ( 0 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
    def __next__ ( self ) :
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
    def __next__ ( self ) :
        self.stream.read ( 1 )
