def main ( ) :
    import sys
    import numpy
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core import loadtxt
    from numpy.core