def main ( ) :
    import sys
    from os import urandom
    from os.path import join
    from os import sep
    from os.path import expanduser
    from os.path import join
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import join
    from os.path import exists
    from os.path import exists
    from os.path import isfile
    from os.path import join
    from os.path import exists
    from os.path import isfile
    from os.path import join
    from os.path import exists
    from os.path import isfile
    from os.path import isfile
    from os.path import join
    from os.path import exists
    from os.path import isfile
    from os.path import isfile
    from os.path import dirname
    from os.path import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import dirname
    from os.path import basename
    from os.walk import isfile
    from os.path import isfile
    from os.path import isfile
    from os.path import dirname
    from os.walk import isfile
    from os.path import isfile
    