def main ( ) :
    import sys
    from numpy.testing import assert_almost_equal
    sx = sy = sx.split ( ',' )
    tx = sy.split ( ',' )
    ty = sy.split ( ',' )
    sx = sy.split ( ',' )
    sy = sy.split ( ',' )
    tx = tx.split ( ',' )
    ty = ty.split ( ',' )
    sx = sx.split ( ',' )
    sy = sy.split ( ',' )
    tx = tx.split ( ',' )
    ty = ty.split ( ',' )
    sy = sy.split ( ',' )
    sx = sy.split ( ',' )
    sy = sy.split ( ',' )
    tx = tx.split ( ',' )
    ty = ty.split ( ',' )
    sx = sx.split ( ',' )
    sy = sy.split ( ',' )
    tx = tx.split ( ',' )
    ty = ty.split ( ',' )
    sx = sy.split ( ',' )
    sy = sy.split ( ',' )
    tx = tx.split ( ',' )
    ty = ty.split ( ',' )
    sx = sy.split ( ',' )
    sy = sy.split ( ',' )
    tx = tx.split ( ',' )
    ty = ty.split ( ',' )
    sy = tx.split ( ',' )
    sx = sy.split ( ',' )
    sy = sy.split ( ',' )
    tx = tx.split ( ',' )
    ty = ty.split ( ',' )
    sy = tx.split ( ',' )
    sx = sy.split ( ',' )
    sy = sy.split ( ',' )
    sx = sy.split ( ',' )
    sy = sy.split ( ',' )
    sx = sx.split ( ',' )
    sy = sy.split ( ',' )
    sy = sy.split ( ',' )
    assert_almost_equal ( sx , sy , sx , sy )
    assert_almost_equal ( sx , sy , sy , 2 )
