def _import ( ) : return open ( '/dev/null' , 'r' )
def read ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) : return read_len
def _import ( ) :
def _import ( ) : return _import ( )
