def check_possible ( field , row_id , number , M ) :
    import os
    import sys
    import os
    import sys
    from csv import writer
    from csv import reader
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
    from csv import DictWriter
