def import math
import os
import sys
import math
import random
import sys
from math import ceil
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import cos
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
from math import sin
