def main ( ) :
    from sys import stdin
    from random import randint
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
