def _import ( ) :
    from itertools import repeat
    from random import randint , randrange
    from random import choice
    from random import choice
    from random import random
    from time import sleep
    from random import random
    from time import sleep
    from random import choice
    from random import choice
    from random import random
    from time import choice
    from random import choice
    from random import choice
    from random import random
    from time import choice
    from random import choice
    from random import random
    from time import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import random
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import random
    from random import choice
    from random import random
    from random import choice
    from random import random
    from random import choice
    from random import random
    from random import choice
    from random import random
    from random import choice
    from random import random
    from random import choice
    from random import random
    from random import choice
    from random import random
    from random import random
    from random import choice
    from random import random
    from random import random
    from random import choice
    from random import random
    from random import choice
    from random import random
    from random import random
    from random import random
    from random import choice
    from random import random as S
