def _ _ main _ _ ( ) : return sys.stdin
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import readline
import time
import time
import time
import time
import time
import time
import time
import maxsize
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import readline
import readline
import readline
import readline
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import readline
import readline
import readline
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import readline
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
import rtime
from rtime
import rtime
from rtime import rtime
from rtime import rtime
from rtime import rtime
from rtime import rtime
from rtime import rtime
from rtime import rtime
from rtime import rtime
from rtime import rtime
from rtime import rtime
from rtime import rtime
