def main ( args ) :
    import sys
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    from string import printable
    