def _ ( * args ) : return sys.stdin.read ( )
INPUT = ''
mod = 1_000_000_007
inf = int ( 1024 ) / 2
def read ( n ) : return sys.stdin.read ( n )
def solve ( ) :
    n , a = [ ] , [ ]
    for i in range ( n ) : a.append ( i )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
def read ( n ) : return sys.stdin.read ( n )
