def _readline ( stream ) : return stream.readline ( )
class Main ( object ) :
    def __init__ ( self , stream ) :
        self.stream = stream
    def readline ( self ) :
        self.stream = stream
        self.stream = stream
        self.stream.write ( stream.read ( ) )
        self.stream.seek ( 0 )
        self.n = self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
    def __next__ ( self ) :
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
        self.stream.read ( 1 )
    