def _import ( ) :
    from struct import Struct , calcsize
    from struct import Struct , calcsize
    from struct import Struct
    from struct import calcsize
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import calcsize
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import calcsize
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct import Struct
    from struct
