def _ _ main _ _ ( ) : return
def main ( ) : return
def MOD ( ) : return 1e9 + 7
def MI ( ) : return 1e9
def ML ( ) : return 1e18
def reader ( * args ) : return None
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
def write ( * args ) : return [ ]
