def _main ( ) :
    from time import time
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.path import join
    from os.path import expanduser
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os import urandom
    from os.path import join
    from os.path import join
    from os import urandom
    from os import urandom
    from os.path import join
    from os.path import join
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os import path as urandom
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.path import join
    from os.remove import join
