def _readline ( ) : return _readline ( )
def readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _INPUT ( ) :
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _newline ( ) : return _readline ( )
def _newline ( ) : return _newline ( )
def _newline ( ) : return _newline ( )
def _newline ( ) : return _newline ( )
def _newline ( ) : return _newline ( )
def _newline ( ) : return _newline ( )
def _newline ( ) : return _newline ( )
def _newline ( ) : return _newline ( )
def _readline ( ) : return _readline ( )
def _newline ( ) : return _newline ( )
def _readline ( ) : return _readline ( )
def _newline ( ) : return _newline ( )
def _readline ( ) : return _readline ( )
def _newline ( ) : return _newline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline
def _readline ( ) : return _readline
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
def _readline ( ) : return _readline ( )
