def _ _ main _ _ ( ) : return
def _ ( ) : return time.time ( ) - prev_date_time
def check_timer ( ) : return time.time ( )
def _ ( ) : return time.time ( ) - prev_date_time
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return time.time ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _ ( )
def _ ( ) : return _
