def pycodejam2014.round2 ( ) :
    import os
    import sys
    import os
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import string
    import random
    import string
    import string
    import string
    import string
    import string
    import string
    import random
    import string
    import string
    import string
    import random
    import string
    import string
    import string
    import random
    import string
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import random
    import string
    import string
    import random
    import string
    import random
    import string
    import string
    import random
    import string
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    import random
    import string
    import random
    import random
    # pycodejam2014.round2
    import string
    import random
    import string
    import random
    import string
    import random
    import string
    import random
    # pycodejam2014.round2
    import string
    import random
    import string
    import random
    # pycodejam2014.round2
    import string
    import string
    import random
    import string
    import string
    import random
    # pycodejam2014.round2
    import string
    import pycodejam2014.round2
    # pycodejam2014.round2
    import string
    import string
    import string
    import string
    import random
    # pycodejam2014.round2
    import string
    import string
    import string
