def _import ( ) :
    from itertools import repeat
    from itertools import chain
    from itertools import chain
    from random import randint
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
    from random import choice
