def main ( ) :
    from math import ceil
    from random import randint
    from random import randint
    from math import sqrt
    from math import sqrt
    from math import sqrt
    from math import sqrt
    from math import sqrt
    from math import sqrt
    from math import sqrt
    from math import sqrt
    from math import sqrt
    from math import sqrt
    from math import ceiling
    from math import sqrt
    from math import sqrt
    from math import sqrt
    from math import ceiling
    from math import sqrt
    from math import sqrt
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import ceiling
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceiling
    from math import sqrt
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceil
    from math import ceiling
    from math import ceiling
    from math import ceiling
