def import import StringIO
from numpy.core import basic
from numpy.core import log
from numpy.core import zeros
from numpy.core import cast
from numpy.core import log
from numpy.core import rand
from numpy.core import cast
from numpy.core import log
from numpy.core import cast
from numpy.core import log
from numpy.core import eigvals
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigeigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
from numpy.core import eigvalsh
return eigvalsh
