def _main ( ) :
    from math import sin , cos , sqrt , log
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from numpy import sin , cos , pow
    from os.path import join
    from os.path import join
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os.path import join
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
    from os import urandom
