def _ _ main _ _ ( * args ) : return args
def main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
def __main ( * args ) : return args
