def _import ( ) :
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import itertools
    import os
    import itertools
    import os
    import sys
    import os
    import sys
    import itertools
    import itertools
    import itertools
    import itertools
    import itertools
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    import sys
    import os
    sys = os
