@ VisibleForTesting static void solve ( ) throws IOException {
  final String filename = "default.in" ;
  final String [ ] inputLines ;
  final String [ ] output = new String [ inputLines . length ] ;
  final File outputDir = new File ( "output" ) ;
  final File outputFile = new File ( outputDir , "output" ) ;
  final File outputDir = new File ( outputDir , "output" ) ;
  final File inputFile = new File ( inputFile , "input" ) ;
  final File outputFile = new File ( outputFile , "output" ) ;
  final Scanner scanner = new Scanner ( inputFile ) ;
  final int i = scanner . nextInt ( ) ;
  final String [ ] inputLines ;
  final int incorrectLineNumbers ;
  final String inputLine ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final String inputFileName ;
  final