def _import ( ) : return open ( '/dev/null' , 'r' )
def read ( ) : return open ( '/dev/null' , 'r' ).read ( )
def _import ( ) : return open ( '/dev/null' , 'w' ).read ( )
def main ( ) :
    fh = sys.stdin
    fh = sys.stdout
    fh = MyInput ( fh )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.write ( '/dev/null' )
    fh.close ( )