def import input_stream
from os import sys
from os import urandom
from io import BytesIO
from os import urandom
from random import randint
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from random import choice
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from random import randint
from os import urandom
from random import random
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from time import time as time
from random import randint
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from random import randint
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from time import time as time
from random import randint
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from random import randint
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os import urandom
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.path import exists
from os.urandom
from os import urandom
try :
    import cPickle as pickle
