def gcj ( ) :
    import numpy as
    import numpy as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as
    import numpy.testing as as as
    import numpy.testing as as
    import numpy.testing as as as
